### ISSUE TITLE
pin or password 

### ISSUE THREAD

**Issue by paulle** [billthefarmer/diary#1]
Thank you for programming a diary app.
I like this program. But for diary I would like to have pin or password. What do you think about?
The calender view in vertikal and horizontal view looks different and the actual date in vertikal is hard to read (grey and dark grey). I attach two screenshots.
Best regards

**Comment by paulle** [comment]
![screenshot_20170506-223109](https://cloud.githubusercontent.com/assets/4852079/25775859/6fbf0e98-32af-11e7-9b50-f3be5d0462c6.png)
![screenshot_20170506-222934](https://cloud.githubusercontent.com/assets/4852079/25775858/6fbccaa2-32af-11e7-84f9-b98a814844fb.png)

**Comment by monolifed** [comment]
Its data is stored in /sdcard/Diary as plain text files. Just putting pin or password without encryption wouldn't prevent people from reading them.

**Comment by billthefarmer** [comment]
The date picker I'm using in this app is a built in part of android. The only part of it that can be changed is whether to show the calendar or the date picker or both, and this has been deprecated in android 7.  It looks like you've got the Material style calendar in portrait and the Holo style calendar in landscape. What version of android is your phone running? I agree with @monolifed, if you want your data secured, you should have a pin or password on the device.

**Comment by paulle** [comment]
I'm using android 7.0

Am 7. Mai 2017 09:20:43 MESZ schrieb Bill Farmer <notifications@github.com>:
>The date picker I'm using in this app is a built in part of android.
>The only part of it that can be changed is whether to show the calendar
>or the date picker or both, and this has been deprecated in android 7. 
>It looks like you've got the Material style calendar in portrait and
>the Holo style calendar in landscape. What version of android is your
>phone running? I agree with @monolifed, if you want your data secured,
>you should have a pin or password on the device.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/billthefarmer/diary/issues/1#issuecomment-299687596

-- 
K-9 Mail

**Comment by billthefarmer** [comment]
Ok, I'll do some more testing.

**Comment by billthefarmer** [comment]
I can't reproduce your phone's behavior on an emulator. I can't force an android 7 device to use the old Holo style date picker. And it doesn't fit on your screen properly.

**Comment by billthefarmer** [comment]
I have released a new version which has the choice of a custom calendar which highlights entries. It also doesn't attempt to change the built in date picker calendar on android 7 phones.

**Comment by paulle** [comment]
Thank you, will try it when it is on f-droid and report.

Am 8. Mai 2017 18:18:59 MESZ schrieb Bill Farmer <notifications@github.com>:
>I have released a new version which has the choice of a custom calendar
>which highlights entries. It also doesn't attempt to change the built
>in date picker calendar on android 7 phones.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/billthefarmer/diary/issues/1#issuecomment-299915238

-- 
K-9 Mail

**Comment by paulle** [comment]
![screenshot_20170511-151753](https://cloud.githubusercontent.com/assets/4852079/25952873/2596a82e-3662-11e7-9f93-641a0adaca19.png)
![screenshot_20170511-151743](https://cloud.githubusercontent.com/assets/4852079/25952872/25903e62-3662-11e7-9a19-374e00cfa7b6.png)
Problem with date picker is solved. Thank you.     see screenshots
