### ISSUE TITLE
Markdown view base path for relative image references

### ISSUE THREAD

**Issue by spaceChRiS** [billthefarmer/diary#10]
The markdown view works great and is able to embed images from the web

    ![text](http://server.tld/image.jpg)

or locally

    ![text](file:///directory/image.jpg)

and should be able to load relative references but I was not able to make it work since I don't know the base path:

    ![text](relative/path/image.jpg)

It would be great if 

    ![text](image.jpg)

would grab the image from the current month directory such that I can keep image files together with the diary entries and easily reference them.

**Comment by billthefarmer** [comment]
The base path is `file:///sdcard/whatever', or `file:///sdcard/Diary` for the diary. As I said [here](https://github.com/billthefarmer/diary/issues/9#issuecomment-304434080), the markdown view is a library. It gets it's markdown parser from [markdownj](https://github.com/myabc/markdownj), which I think is based on the possibly original markdown [Markdown Syntax](https://daringfireball.net/projects/markdown/syntax).

**Comment by spaceChRiS** [comment]
Hm, relative links don't seem to work at all. I took an absolute link starting with `file:///` that worked and replaced it by `../../../../../../../../../../original_absolute_link` which should bring me to the image starting from whatever position in the directory tree.

Should I ask this question upstream?

**Comment by billthefarmer** [comment]
There isn't an absolute path for the internal HTML to create a relative path to. The code gets the text from the text view or from the relevant file, depending on context, and loads it into the markdown view, which converts it to HTML and loads it into the internal web view. The generated HTML never sees the light of day outside the markdown view. You can pass a file to the markdown view, which this app doesn't do as the text is already loaded into the text view by all the code originally created by Josep, but I doubt if the path would get to the web view.

**Comment by spaceChRiS** [comment]
That means, the working directory in that context is that of the internal web view? Unfortunately I have no idea how to find it out, on standard Linux it would be easy, but the weird android one app one user model complicates things here. Probably it's best to bring this question upstream, which I'd like to do in my next time slot. Or probably on android stack exchange.

**Comment by spaceChRiS** [comment]
Btw, do you have access to the html code generated by the MarkdownView library? Could you tell me what html code is rendered by a markdown line such as

    ![test](path/image.jpg)

please?

**Comment by billthefarmer** [comment]
The only way to do that would be to clone it and put some debugging code in. But markdown is simple, the output should be `<img src="path/image.jpg" alt="test" />`. I don't think you can have a relative file path, see [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme). The syntax is `file://host/path`.

**Comment by billthefarmer** [comment]
A possible solution is to use text substitution. I could replace `(~/whatever)` with `(file:///path/to/current/entry/whatever)`, so if you put `![cat](~/cat.jpg)`, you would get `![cat](file:///sdcard/Diary/<year>/<month>/<day>/cat.jpg)`. The potential problem with this is that some, like me, use that symbol meaning about, like 'pi (~ 3.14)'. You would have to put a space in 'pi ( ~ 3.14)'.

**Comment by billthefarmer** [comment]
Ok, that works. If you put `![cat](~/cat.jpg)`, the markdown view sees `![cat](file:///storage/emulated/0/Diary/2017/05/cat.jpg)` and displays the image in the current entry folder.

**Comment by billthefarmer** [comment]
I have posted a new version containing this and lots of other good stuff including animated transitions for editing, swipe left and right with some animation, German translation, my fork of the custom calendar as it needed fixing and image width restriction.

**Comment by spaceChRiS** [comment]
Your pace is amazing :) Thank you!

In other context, such as https://stackoverflow.com/questions/15764242/is-it-possible-to-make-relative-link-to-image-in-a-markdown-file-in-a-gist, relative links work, therefore I was wondering if this applies here as well.

**Comment by billthefarmer** [comment]
The CSS I have included limits the width of images, which seems to be fairly standard practice in android apps. I should probably limit the height as well. So small images less than the screen height or width won't be affected.
MarkdownView is simple, it just uses a background task to load the text, runs it through Markdownj, prepends some HTML to load the CSS if it exists, and loads the HTML into the web view. It would be trivial to load a second CSS file, but outside the scope of this app.
This is intended to be a simple diary app, not a comprehensive markdown viewer

**Comment by spaceChRiS** [comment]
Actually, I personally don't care too much. For me, it is a perfectly solution. I have the features that I personally need. However, I can see some potential issues, and this is why I continued to make suggestions. Anyway, for me personally, the features are just fine. To complete the topic, my thoughts:

1. Without any zooming possibility, any restriction of the image size seems difficult. Markdown has no syntax for a per picture decision, therefore, the default should be user selectable and it should be possible to overwrite it per picture. Having the user editable css seemed to be a simple solution for setting the default with the benefit of the ability to customize the appearance further.
2. Expanding the tilde solves the issue of relative file reference, but results in non-standard Markdown. When I want to view my diary entries on the home computer, I can easily go from Markdown to any format by a converter or use a dedicated viewer. These programs expect relative references to refer to the path the Markdown document is located. Using the tilde breaks this. Probably, search & replace should detect and analyze the full Markdown statement and insert the missing path in relative links

```
      ![test](relative/path/image.jpg "text") --> ![test](/absolute/path/relative/path/image.jpg "text")
```

That all does not mean that I am not fine and happy with the current state, just some thoughts.

**Comment by billthefarmer** [comment]
Having had another look, I have found another reason why relative paths don't work, the HTML is passed to the webview with a fake base URL , [here](https://github.com/falnatsheh/MarkdownView/blob/master/MarkdownView/markdownview/src/main/java/us/feras/mdv/MarkdownView.java#L141). It should be possible to fork [MarkdownView](https://github.com/falnatsheh/MarkdownView) and produce a version that will accept a real base URL.

**Comment by billthefarmer** [comment]
The reason why zooming doesn't work is because it isn't enabled in the webview, not because of the CSS.

**Comment by billthefarmer** [comment]
I have forked MarkdownView and fixed the fake base URL. I have enabled zoom on the webview which works as expected using pinch and expand gestures. The text substitution is now redundant, `[text](image.jpg)` now displays the image if it is in the same folder as the diary page.

**Comment by spaceChRiS** [comment]
Great! You are amazing :-)! Thanks for all the effort you put into this little app! Now it's almost perfect for me :-D. If it now would write my diary automatically … ;-)
