### ISSUE TITLE
Partial abscence of the symbol "new line" (in read mode)

### ISSUE THREAD

**Issue by rendel470** [billthefarmer/diary#100]
Perhaps this moment even shocked me a little. 
In "edit mode", there is a "New line" symbol, and in "read mode", the "new line" symbol suddenly disappears and a "Space" symbol appears instead!

__Edit mode__
![Screenshot_20190724185454](https://user-images.githubusercontent.com/53268744/61809551-33b5b180-ae46-11e9-8922-9d25060afe3f.png)

__Read mode__
![Screenshot_20190724185524](https://user-images.githubusercontent.com/53268744/61809635-652e7d00-ae46-11e9-8c48-3a4c1082d221.png)

But then I looked more closely and it turned out that the character "space" (in read mode) does not always replace the character "new line".

If you put the "newline" character only once, then in read mode, instead of the "newline" character, there will be a "space" character.

But if you put two characters "new line", then in read mode, the second character "new line" will look like "new line" (and the first of the two characters looks like ... or is it a "space" or is it like a "new line")("new line" and "new line" or "space" and "new line"?)

And I realized that this is an ordinary bug that (someday) will be caught and removed forever.
At least, I hope that this bug will be eliminated someday.

The program is convenient, but I prefer once (not twice) to enter the character "New line" (Often see in the reading mode, the symbol "space" than the symbol "new line")

**Comment by billthefarmer** [comment]
This is how markdown is supposed to work - See [Paragraphs and Line Breaks](https://daringfireball.net/projects/markdown/syntax#p)

**Comment by rendel470** [comment]
Good. Understood. Thank you for the explanation! 
I'm going to close this thread now. (or this will make the moderator?)
