### ISSUE TITLE
Support multiple diaries

### ISSUE THREAD

**Issue by hieutvan** [billthefarmer/diary#103]
E.g. one for dreams, one for normal life…

**Comment by billthefarmer** [comment]
You can achieve this by using multiple diary folders or by using the index feature.

**Comment by hieutvan** [comment]
Could you please show me how to do that, in each option?

**Comment by billthefarmer** [comment]
For multiple diary folders the default folder is `Diary`. Go to Settings->Folder and change it to `Dreams`. You now have two diaries, one called `Diary` and one called `Dreams` and you can switch between the two in Settings.

For the index feature go to Settings->Use index and select the tick box. The default index page is 1st Jan 2000. Use the index page as an index for various pages of whatever you want using date URI links:

`[Dreams](date:1/2/2000)`
`[More dreams](date:1/3/2000)`

Use the index feature tick box in settings to switch between diaries. All this is documented in the [README](https://github.com/billthefarmer/diary/blob/master/README.md#index) here and in the help file that gets loaded when you first use the app.
