### ISSUE TITLE
[FEATURE REQUEST] Extended Export functionality

### ISSUE THREAD

**Issue by nottheend** [billthefarmer/diary#104]
It would be handy to have a more advanced **Backup/Export Function**

Two possible options:
- merge all entries in one file for export, it'll be more easy then to upload somewhere
- add option to store diary entries directly on cloud storage, esp. [NextCloud](https://docs.nextcloud.com/server/stable/developer_manual/android_library/library_installation.html)

**Comment by nottheend** [comment]
As I saw #42, NextCloud might not an option.

Remains the "1 File solution" as Backup

**Comment by billthefarmer** [comment]
OK, I have releases a new version with a backup option. This writes a zip file containing all entries with the same name as the diary folder, default `Diary.zip`. It does not include the diary folder so it may be restored to a different folder.

**Comment by nottheend** [comment]
Sounds great! That was exactly what I was looking for 👍 

Just I'm not aware of the build process in this project and therefore can't test it right now

**Comment by citizen2947294** [comment]
I just tested this. It seems to export all the text files correctly. It does not export any of the pictures that were copied into the diary with "Add media..." or any other media/files from the directories. Is it much trouble to get it to export the other pictures/media/files too?

**Comment by nottheend** [comment]
Confirm: The F-Droid version works smoothly with the Backup, thanks!

**Comment by nottheend** [comment]
To reduce confusion: would be nice if the Backup could be stored in the root of the ```Diary``` folder, configured in the app

**Comment by billthefarmer** [comment]
Thereby goes a recursive backup backup inclusion feature...  :squirrel:
