### ISSUE TITLE
Asking for support

### ISSUE THREAD

**Issue by gloeyisk** [billthefarmer/diary#107]
This report is not related with issue, but I love Dark theme more. Could you change the theme while opening the diary the same as well as in editor menu?

**Comment by billthefarmer** [comment]
You need to add a styles file, see #106

**Comment by gloeyisk** [comment]
> You need to add a styles file, see #106

Got that right, thanks!

**Comment by gloeyisk** [comment]
Hello @billthefarmer, just a quick question:
Is it possible to change the background color using hex editor rather than color name?
