### ISSUE TITLE
Could it support the math equations?

### ISSUE THREAD

**Issue by montanus2019** [billthefarmer/diary#108]
I use this app as my diary notebook, it's very helpful for me. I think if it could support the math equations, it would be an entire notebook for our users.Thx.

**Comment by billthefarmer** [comment]
It's already possible to do this by using some HTML referencing an external web site if the phone is online...
```html
\sum_{i=1}^{n} x_{i}^{2}

<img src="http://www.sciweavers.org/tex2img.php?eq=%5Csum_%7Bi%3D1%7D%5E%7Bn%7D%20x_%7Bi%7D%5E%7B2%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="\sum_{i=1}^{n} x_{i}^{2}" width="47" height="50" />
```
![Screenshot_20191014-095805](https://user-images.githubusercontent.com/3448386/66740062-1521ee00-ee6a-11e9-8107-c773e97f8d96.png)
![Screenshot_20191014-095813](https://user-images.githubusercontent.com/3448386/66740090-25d26400-ee6a-11e9-85d1-dfc2818ee061.png)

See https://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog.

However to run LaTeX on a phone AFAIK requires rooting the phone and installing a Linux distribution and the TeX package is over 2Gb.

**Comment by montanus2019** [comment]
Thank you. I get it, your solution is good enough for me, thx again.

**Comment by billthefarmer** [comment]
It can be a lot simpler and still work...
```html
<img src="http://www.sciweavers.org/tex2img.php?eq=\sum_{i=1}^{n} x_{i}^{2}&fs=16&ff=arev" />
```
