### ISSUE TITLE
Relative links don't work (wishlist bug)

### ISSUE THREAD

**Issue by autonomouse** [billthefarmer/diary#11]
The docs say that "you may store images in the diary storage folders and reference them in diary entries so markdown text ```![cat](cat.jpg)``` will display cat.jpg stored in the current month folder which is Diary/<year>/<month> on the sdcard."

This is great, but I need a way to refer to image in a different folder, say ```file:///storage/emulated/0/Diary/media/picture.jpg```

Using this directly does work, but I also like this to work with another markdown piece of software on my PC so I'd really like to use ../../media/picture.jpg

Also I don't like overloading ~ as I'm on a Linux machine

Are there any plans to introduce the use of relative links?

Love your work, by the way :-)

**Comment by billthefarmer** [comment]
I tested this when I was developing the base URL function which implements the links. You are quite right, it doesn't work. This is probably a function of the android system or the web view I am using. I think it is the `../../something` part that doesn't work as you can't have a path that's further down the file system than the base URL. I don't think there is anything I can do about it without reverting to path substitution which I have just removed to get rid of the `~`. One possible workaround would be to use symbolic links in the diary folders to your media folder, say

    Diary/2017/06/media -> /sdcard/Diary/media

Then you could use `[picture](media/picture.jpg)` in a diary entry. The downside is that I tried to create symbolic links on my devices, even using bash, and couldn't get it to work.

**Comment by billthefarmer** [comment]
I've just written a load of old cobblers. I just tested what you suggested in the current version and it works. F-Droid are somewhat slow at the moment, they are now two versions behind. The older release build failed because it couldn't get some of the gradle libraries it needed several days ago. Then yesterday they built both releases one after the other, but they haven't appeared yet in the repository. What you suggested should work in both.

**Comment by spaceChRiS** [comment]
I can confirm that relative links with `../` work, and, that f-droid has the most recent version available now :-D.

**Comment by autonomouse** [comment]
Not working yet, but I'll keep an eye on it. F-droid has my version at 1.0.4

**Comment by autonomouse** [comment]
Just got the update to 1.0.6. Works perfectly. Thanks!

**Comment by autonomouse** [comment]
Just got the update to 1.0.6. Works perfectly. Thanks!
