### ISSUE TITLE
cannot edit CSS style

### ISSUE THREAD

**Issue by madeindjs** [billthefarmer/diary#111]
I tried to update CSS style on Markdown but it seem not working on version 1.54.

To do so I just copy / paste this markdown CSS : https://raw.githubusercontent.com/falnatsheh/MarkdownView/master/css-themes/paperwhite.css . I also tried to just put a simple CSS rule but it seem to not save content because I can't see it when I open setings again..

**Comment by billthefarmer** [comment]
You must use the `accept` tick button to save the edits. See https://github.com/billthefarmer/diary/issues/106#issuecomment-529889834.

**Comment by madeindjs** [comment]
It works when I create `css/styles.css` file Ising another application. But even after I cannot edit content using Diary..

**Comment by billthefarmer** [comment]
I have released a new version with extra save and error dialogs and with file checks removed.

**Comment by madeindjs** [comment]
Thank, it's works on [v1.55](https://github.com/billthefarmer/diary/releases/tag/v1.55).
