### ISSUE TITLE
A share button

### ISSUE THREAD

**Issue by SophieYoonseo** [billthefarmer/diary#113]
I think it'd be nice to add a Share button.
After adding a schedule, I want to share it with my friends.
What do you think of my opinion?

**Comment by billthefarmer** [comment]
I have looked at this. It depends on what exactly you want to share. It's easily possible to share the markdown text, a bit more complicated to share the displayed HTML text. I will investigate.

**Comment by billthefarmer** [comment]
I have implemented this in the current version.

**Comment by SophieYoonseo** [comment]
Really?? I am also trying on this issue. I will be doing a pull request tomorrow. I tried to send text and images together to promote the app. Please take a look at my ideas tomorrow.
