### ISSUE TITLE
Sharing how to do checklists

### ISSUE THREAD

**Issue by amunizp** [billthefarmer/diary#114]
In case this is helpful, I created an index page that I later copy and paste for each day. Thought I would share how I was able to do checklists.

```
#how was your day

#how was your mood

#three things you did well
1.
2.
3.

#moment of gratitude

#Todos
##Todo Tomorrow

- <input type="checkbox" >
- <input type="checkbox" >
- <input type="checkbox" >

##Todo next week

- <input type="checkbox" >
- <input type="checkbox" >
- <input type="checkbox" >

##Todo next Month

- <input type="checkbox" >
- <input type="checkbox" >
- <input type="checkbox" >
```

Would creating a CSS and a JS enable to automate this process and avoid me having to do copy paste every day? Something like create a template?

**Comment by billthefarmer** [comment]
Unfortunately web JavaScript can only access files through an HTML input tag which involves the user selecting the file. This doesn't seem to work in android.

However you can do almost anything else with it, including rewriting the whole web page. You could do this with some code which checked for a particular element which would be replaced by your template with things like dates filled in. Something like this...
```html
<a id="template">
```
```javascript
window.onload = function() {
   document.getElementById("template").outerHTML = "your template HTML";
};
```

**Comment by billthefarmer** [comment]
Having realised that what I suggested above will get overwritten whenever the entry is visited, I have implemented an optional template page which will be in the next version.

**Comment by amunizp** [comment]
Amazing! Thanks a million!
