### ISSUE TITLE
add calendar entries to Diary?

### ISSUE THREAD

**Issue by xandro0777** [billthefarmer/diary#118]
It works the other way around - but in some situations it would be really handy to have calendar entries added to the diary in some situations so it would be easier to comment on todays and past events.

Don't think adding all entries from all calendars without asking would be such a great idea though. Maybe when editing a day or week an option could be offered to import them?

**Comment by billthefarmer** [comment]
I will look at this - it would be limited to adding entries for the current day, as is the add media function.

**Comment by billthefarmer** [comment]
Ok, this will be in the next version.

**Comment by xandro0777** [comment]
Thanks, looking forward to this.
