### ISSUE TITLE
double tap to swich to edit mode where tapped

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [billthefarmer/diary#120]
Hi,

I use diary daily with lots of success and am very happy with it but I was wondering if you would be considering adding this functionnality :)

Thanks !

**Comment by billthefarmer** [comment]
It's possible, but there is no direct correlation between touch position in the markdown view and cursor position in the edit view. I will investigate.

**Comment by thiswillbeyourgithub** [comment]
Thank you immensely !
