### ISSUE TITLE
Character count with artificial restriction

### ISSUE THREAD

**Issue by beefeater7** [billthefarmer/diary#121]
It would be neat to see the length of an entry while typing. 

I would use an option for self restricting length of entries: It's a 'feature' of calendar style diaries to allot limited space for every day. 

Hard limits could help the user establish a daily habit, as opposed to writing sporadic mini-essays (I am prone to this).

**Comment by billthefarmer** [comment]
It's a nice idea, but there is no space on a small(ish) phone for it. Screen shots from a Moto G (4½ inch).

![Screenshot_20200104-100621 1](https://user-images.githubusercontent.com/3448386/71764030-bc974580-2eda-11ea-9c13-80c48c4cc3b5.png)

![Screenshot_20200104-100527 1](https://user-images.githubusercontent.com/3448386/71764069-f36d5b80-2eda-11ea-80e8-283b4ec8e311.png)

**Comment by beefeater7** [comment]
I don't know what the GUI framework is capable of but here are some ideas. 
- Some apps use a horizontal slider to fit more elements in a bar, but that's probably bloaty. 
- Char count may not be important until it nears a given set limit. Comment systems show the overflow when you're in the red, Twitter too right? 
- Not sure where to display it. Tooltip by the caret maybe?

**Comment by billthefarmer** [comment]
I am not going to implement this because it is unnecessary and has the potential to make a mess of the UI.
