### ISSUE TITLE
Unable to load Openstreetmap

### ISSUE THREAD

**Issue by RocketJannis** [billthefarmer/diary#124]
The Map cannot be loaded because the website is not accessed via https

Possible solutions: use https or allow cleatext traffic in the AndroidManifest.xml

![Screenshot_20200204-231056_Diary_1_1](https://user-images.githubusercontent.com/38166566/73792188-16be4b80-47a4-11ea-96c6-6c7d5da0839b.png)

**Comment by billthefarmer** [comment]
OK, I have done both as the http://www.sciweavers.org site referred to in the help and README for embedding Latex doesn't appear to support HTTPS. That will be in the next version.
