### ISSUE TITLE
Empty pages is stored by app

### ISSUE THREAD

**Issue by marcoM32** [billthefarmer/diary#127]
If the entry in the editor is trim empty that is, it contains only empty spaces or characters "new line" the page should not be saved as it does not contain anything important...
At this moment, to delete a page with only spaces, it is necessary to delete all the characters inside it; is possible check this behavior?

**Comment by billthefarmer** [comment]
This part of the app is original code written by Josep which I have not changed. It just checks the length, and if zero deletes the file and it's parents if necessary. The easiest way to delete a diary page is to double tap to get the edit popup menu, select all and cut. Then when you close the app or move to another page the file gets deleted.

**Comment by marcoM32** [comment]
Yes the convention is that; I was wrong to add them! you did well to eliminate them.
Thank you

**Comment by marcoM32** [comment]
OK no problem, I close this unnecessary issue
