### ISSUE TITLE
Possibility to improve the modal layout of screen "about of"

### ISSUE THREAD

**Issue by marcoM32** [billthefarmer/diary#128]
In this moment the layout of "about of" screen contains a lot of info but these are very bruised: is possible add some new line to improve the experience?

This is an example of what has been done in the [forecastie ](https://github.com/martykan/forecastie) project:

<img width="200" src="https://user-images.githubusercontent.com/16719549/79725463-8d6dde00-82e9-11ea-9820-719dc307ab35.jpg" />

**Comment by billthefarmer** [comment]
I assume you mean the Italian version...
![Screenshot_20200420-095001 1](https://user-images.githubusercontent.com/3448386/79734501-b8a6fc00-82ee-11ea-9733-d6846463dae6.png)
It's a bit of a mixed bag as it's only partially translated. I agree it would look better with the the name of the app as the title. The English version is worse as it has credits for all the translators, which ought to appear somewhere. I will experiment.

**Comment by billthefarmer** [comment]
How about...
![Screenshot_20200420-111255 1](https://user-images.githubusercontent.com/3448386/79741047-7c789900-82f8-11ea-86db-6f404fb8408e.png)
and
![Screenshot_20200420-111418 1](https://user-images.githubusercontent.com/3448386/79740862-40ddcf00-82f8-11ea-929e-dad2a7ab43c7.png)

**Comment by billthefarmer** [comment]
Changing languages while things are going on certainly confuses Android...
![Screenshot_20200420-113345 1](https://user-images.githubusercontent.com/3448386/79742629-0aee1a00-82fb-11ea-89ce-fa8c1953a8a9.png)

**Comment by marcoM32** [comment]
I like this new layout, I will have to wait for the new version to be published on f-droid to see the changes but from the photos you showed me it seems to me that it is much better than before

Thanks alot for your work
