### ISSUE TITLE
Diary changes the modification date on the original images

### ISSUE THREAD

**Issue by Hund** [billthefarmer/diary#129]
I started using Diary yesterday, 1.64 from F-Droid on my Pixel 3a.

I added some entries in the past with images. I have the option to copy the images, which works fine, but for some reason the application changes the modification date on the original images as well.

Thankfully I keep a backup of my photos so I can easily restore them. I really hope that this is a freak bug or something and not a feature.

**Comment by billthefarmer** [comment]
I can't reproduce this, I have tested on two different devices, both through the gallery and through the built in file manager. I didn't write this particular bit of code, it was a contribution, it is [here](https://github.com/billthefarmer/diary/blob/master/src/main/java/org/billthefarmer/diary/FileUtils.java#L530). It just opens a file input stream and copies the file to a file output stream. Are you sure you didn't look at the images using some other app before adding them to the diary?

**Comment by Hund** [comment]
I'm pretty sure. I can't see what application that would be. I can't reproduce it now either. :/
