### ISSUE TITLE
Receiving “send to” images

### ISSUE THREAD

**Issue by spaceChRiS** [billthefarmer/diary#13]
It is hard to get a path including file name into the clipboard on android. Therefore I suggest to register diary to be able to receive image “send to” messages (don't know the android standard name for it). diary could then open with a date picker, the current or last edited date highlighted, to find out which day to append the link. Ideally, this functionality could be combined with #12 where the dialog described there is opened after specifying the date.

**Comment by billthefarmer** [comment]
They don't make it easy. I've got two different file managers on my devices, the built in one that came with Cyanogenmod which is also on F-Droid, and OI File Manager. This is what I get, OI File Manager first:
```
I/ActivityManager(  496): START u0 {act=android.intent.action.SEND typ=image/png flg=0x3000001 cmp=org.billthefarmer.diary/.Diary (has clip) (has extras)} from pid 11261
I/ActivityManager(  496): Start proc org.billthefarmer.diary for activity org.billthefarmer.diary/.Diary: pid=11346 uid=10189 gids={50189, 1028, 1015, 3003}
D/Diary   (11346): Type image/png
D/Diary   (11346): Clip ClipData { image/png {U:content://org.openintents.filemanager/storage/emulated/0/Download/icon.png} }
D/Diary   (11346): Key android.intent.extra.SUBJECT: icon.png
D/Diary   (11346): Key android.intent.extra.STREAM: content://org.openintents.filemanager/storage/emulated/0/Download/icon.png
I/Timeline(  496): Timeline: Activity_windows_visible id: ActivityRecord{4298c260 u0 org.billthefarmer.diary/.Diary t10} time:11903301
I/ActivityManager(  496): START u0 {act=android.intent.action.SEND typ=image/png flg=0x17000001 cmp=org.billthefarmer.diary/.Diary (has clip) (has extras)} from pid 11448
D/Diary   (11346): Type image/png
D/Diary   (11346): Clip ClipData { image/png {U:file:///storage/emulated/legacy/Download/blue.png} }
D/Diary   (11346): Key android.intent.extra.STREAM: file:///storage/emulated/legacy/Download/blue.png
```
So I installed two more file managers from F-Droid - File Manager version 2.2.2, which didn't pick up Diary in the list of apps to send to, and File Manager Pro, which sent the image path. So there's no guarantee that any given file manager will work or send a usable file path.

**Comment by billthefarmer** [comment]
They don't make it easy. I've got two different file managers on my devices, the built in one that came with Cyanogenmod which is also on F-Droid, and OI File Manager. This is what I get, OI File Manager first:
```
I/ActivityManager(  496): START u0 {act=android.intent.action.SEND typ=image/png flg=0x3000001 cmp=org.billthefarmer.diary/.Diary (has clip) (has extras)} from pid 11261
I/ActivityManager(  496): Start proc org.billthefarmer.diary for activity org.billthefarmer.diary/.Diary: pid=11346 uid=10189 gids={50189, 1028, 1015, 3003}
D/Diary   (11346): Type image/png
D/Diary   (11346): Clip ClipData { image/png {U:content://org.openintents.filemanager/storage/emulated/0/Download/icon.png} }
D/Diary   (11346): Key android.intent.extra.SUBJECT: icon.png
D/Diary   (11346): Key android.intent.extra.STREAM: content://org.openintents.filemanager/storage/emulated/0/Download/icon.png
I/Timeline(  496): Timeline: Activity_windows_visible id: ActivityRecord{4298c260 u0 org.billthefarmer.diary/.Diary t10} time:11903301
I/ActivityManager(  496): START u0 {act=android.intent.action.SEND typ=image/png flg=0x17000001 cmp=org.billthefarmer.diary/.Diary (has clip) (has extras)} from pid 11448
D/Diary   (11346): Type image/png
D/Diary   (11346): Clip ClipData { image/png {U:file:///storage/emulated/legacy/Download/blue.png} }
D/Diary   (11346): Key android.intent.extra.STREAM: file:///storage/emulated/legacy/Download/blue.png
```
So I installed two more file managers from F-Droid - (simple) File Manager, which didn't pick up Diary in the list of apps to send to, and File Manager Pro, which sent the image path. So there's no guarantee that any given file manager will work or send a usable file path.

**Comment by billthefarmer** [comment]
Having investigated what the various file managers are actually sending, I have got all four of them to work, including sending multiple images for three of them. The images are appended to the current page which is always today, because android starts a new instance of Diary, even if it already running, which ignores all the good work by Josep Portella Florit to remember the current page. I assume the content paths sent by OI File Manager will stop working if you uninstall it.

**Comment by billthefarmer** [comment]
From the logging above and also looking at the source code of one to see why it didn't work. There is no control of what a file manager sends and how android fires up your app. You specify what you would like to get.
```
      <intent-filter>
        <action android:name="android.intent.action.SEND" />
        <action android:name="android.intent.action.SEND_MULTIPLE"/>
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="image/*" />
      </intent-filter>
```
See [Receiving an implicit intent](https://developer.android.com/guide/components/intents-filters.html#Receiving) and [Intent resolution](https://developer.android.com/guide/components/intents-filters.html#Resolution). This is what I get from a file manager and an image viewer. It's the same image, they both work.
```
![](file:///storage/emulated/0/Diary/images/P1020599.JPG)
![](content://media/external/images/media/9662)
```
Attempting to use the date picker is the next stage. That's a bit more difficult, you have to intercept it when the user has picked a date.

**Comment by billthefarmer** [comment]
Ok, that works. The image or images are always appended to the page chosen because the app has just been fired up and there is no cursor position.
