### ISSUE TITLE
Insert and play video solution

### ISSUE THREAD

**Issue by JackalZhao** [billthefarmer/diary#131]
After my testing, the Diary do can play videos, but requires inserting videos like this: 

```
<video id="video" controls="" preload="none"> <source src="/sdcard/Diary/video example.mp4" > </video>
```

And audios can be insert in this form: 

```
<audio src='/sdcard/Diary/audio example.mp4' controls><a href='/sdcard/Diary/audio example.mp4'>audio example</a></audio>
```

If Diary use these html fromat to insert audios and videos, it won't need to transform the blank space into `%20` and the file path would looks more concise. 

So here is my feature request: when inserting audio or videos, Diary can also copy the file to it's folder, just like processing images. And we can make a media file type filter so we can customize the behavior when inserting a media file, here is an example: 

We set one filter for "*,mp4, *.mkv" , the filter content could be: 

```
<video id="video" controls="" preload="none"> <source src="${filefullname}" > ${filename} </video>
```

So we would be able to customize different parameters when inserting different media files. 

I wish this suggestion could be adopted.

**Comment by billthefarmer** [comment]
I am not sure what you mean. The templates used are...
```java
    public final static String AUDIO_TEMPLATE =
        "<audio controls src=\"%s\"></audio>\n";
    public final static String VIDEO_TEMPLATE =
        "<video controls src=\"%s\"></video>\n";
```
It is not necessary to use the `<source>` element unless you have multiple sources.
