### ISSUE TITLE
The image size render is having problem

### ISSUE THREAD

**Issue by JackalZhao** [billthefarmer/diary#132]
I'm using an Android 10 device, and the rendered page can be shrink by two fingers when there is a large image in the entry, the canves( or page) size is actually bigger than the screen width. 

So when inserting an image, it would be tremendously big, so that I need to shrink the page. When shrinking or expanding the page size, because I'm using two fingers, it occasionally jump to last month or next month. 

So I wish the pictures could automaticlly fit the page size. 

The pictures below speaks the problem: 

![image1](https://s1.ax1x.com/2020/04/25/JsDmmF.jpg)

![image2](https://s1.ax1x.com/2020/04/25/JsDZOU.jpg)

**Comment by billthefarmer** [comment]
The embedded styles file limits images, videos and iframes (used for maps) to the page width. You can use your own styles and include the embedded one or not. See [README](https://github.com/billthefarmer/diary#styles).

**Comment by billthefarmer** [comment]
![Screenshot_20200427-084251_Diary 1](https://user-images.githubusercontent.com/3448386/80346812-4345a900-8863-11ea-9ea2-cc18b8d5b0d7.jpg)
![Screenshot_20200427-084543_Diary 1](https://user-images.githubusercontent.com/3448386/80347016-9cadd800-8863-11ea-9c32-bdfc1d1b49fd.jpg)
