### ISSUE TITLE
I wish Diary could update it's MardDown engine

### ISSUE THREAD

**Issue by JackalZhao** [billthefarmer/diary#133]
Just now I found that Diary markdown don't support code block, then I realized that it's markdown engine might be too old,. I wish it can support the new engine like markdown extra.

**Comment by JackalZhao** [comment]
@gsantner Hopefully this Diary app could draw some intention of top developers. It's potential is so big.

**Comment by billthefarmer** [comment]
Diary supports code blocks using four blanks, it doesn't support code fences. The library used is, IMHO, good enough for a diary. It's not Github.
