### ISSUE TITLE
feature request : fill today with last entry's content + thanks

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [billthefarmer/diary#136]
Hi,

I use diary to keep track of my medication, time taken, dosage, weight etc.

These tend to look the same and to have the same template, it would be really useful for me if you could add an option to fill up the content of the day with the content of the last entry, this way I would just have to edit a few things if it changed, otherwise leave it as it is.

Do you think that could be done? 

Thanks for reading!

**Comment by thiswillbeyourgithub** [comment]
also, I have made a script to extract data from diary and import it in a database in R language, if someone is interested I put it over there : [data importer](https://github.com/thiswillbeyourgithub/Methylphenidate-simulator/blob/master/MPH%20data%20importer%20from%20diary%20to%20anki.R)

While I'm at it, if you add the feature, this would work well with other presaved templates, as mentionned in #54. For example I'm seeing a menu with the first choice "fill as last entry" and other choices "template #2" "template #3" etc. But I'm getting wayy ahead of myself, just suggesting you know? But that would be useful for people keeping logs and diaries. What do you think ?

Thanks again!

**Comment by billthefarmer** [comment]
There are already optional templates. You can have as many templates at you like, you just need to pick which one in the settings.

**Comment by thiswillbeyourgithub** [comment]
Thanks, sorry I didn't pay more attention.
