### ISSUE TITLE
Missing setting for using diary in English instead of localised language

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#140]
There should be a possibility to switch the app's language manually, at least to switch between English and the localised language.

Currently, Diary starts in the system language (which is German in my case), without any chance to switch to English.
This would be useful in case of bad translations as well as issues like bug reports out feature requests. ;)

**Comment by billthefarmer** [comment]
If you swipe up and down on the custom calendar it will show the next or previous year. https://github.com/billthefarmer/diary#swipe-up-and-down. Or use the date picker and tap the year to get a year picker.

**Comment by just-Nob** [comment]
It's not that important - sometimes, it would be a little convenient. ;)

I know that feature by some other apps, e.g. Tibor Kaputa's _Simple mobile tools_ (also hosted on F-Droid).
Of I'm going to describe a bug or feature request, it's handy to switch to English for a better description (otherwise I had to guess the English designators).

**Comment by billthefarmer** [comment]
If you find bad translations in apps you can always send a correction to the developer. I get corrections and translations for my apps. If it is an open source android app, the text strings are usually in `src/main/res/values/strings.xml' and 'src/main/res/values-de/strings.xml' for the German translation &ndash; https://github.com/billthefarmer/diary/blob/master/src/main/res/values/strings.xml. The strings for the custom calendar setting...
```xml
  <string name="calendar">Calendar</string>
  <string name="pref_calendar">Use custom calendar</string>
  <string name="pref_calendar_summ">
    Use custom calendar rather than date picker
  </string>

  <string name="calendar">Kalender</string>
  <string name="pref_calendar">Verwende app-eigenen Kalender</string>
  <string name="pref_calendar_summ">
    Nutze den app-eigenen Kalender statt der nativen Datumsauswahl
  </string>
```
