### ISSUE TITLE
Date picker is unexpedient for switching to "random" dates

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#141]
Imagine you want to jump to a special date that's about 10 years ago. Then you have to tap about 120 times on the left "month arrow...

I would appreciate the direct entry of the year and month as an alternative.

**Comment by billthefarmer** [comment]
If you swipe up and down on the custom calendar it will show the next or previous year. https://github.com/billthefarmer/diary#swipe-up-and-down. Or use the date picker and tap the year to get a year picker.

**Comment by just-Nob** [comment]
Thanks for that hint, I didn't recognised it before.

I tried to swipe up and down: It works, but it's very tenacious on my phone (BQ Aquaris X Pro with Snapdragon 635 I guess, currently running LineageOS 17.1).

Tapping on the year to open a year picker doesn't work at all. :(

**Comment by billthefarmer** [comment]
I mean the year at top left in the date picker. This is on LineageOs 14.1, android 7.1.2 on a Moto G.

![Screenshot_20200608-130433 1](https://user-images.githubusercontent.com/3448386/84028517-c7be3800-a988-11ea-8480-cbdbe808f8fc.png)

**Comment by just-Nob** [comment]
I guess that may be the reason why I wasn't able to find that feature - my date picker looks a little different on my phone (LOS 17.1 on BQ Aquaris X Pro):
![Screenshot_20200608-194417_Tagebuch](https://user-images.githubusercontent.com/25401767/84083293-a3427a00-a9e1-11ea-8729-848f628d8a2c.png)

**Comment by billthefarmer** [comment]
I don't think you have switched to the android date picker in the settings &ndash; https://github.com/billthefarmer/diary#settings.

![Screenshot_20200609-084004 1](https://user-images.githubusercontent.com/3448386/84119894-f1309f80-aa2c-11ea-9a69-e58118a44559.png)

**Comment by just-Nob** [comment]
OK, it seems that there was some misunderstanding.

**_I_** thought that the pickable year was part of the **custom** calendar.
Indeed, of I switch to the system's calendar / date picker, it looks like the screenshot sent by you, and I'm able to tap on the year for selecting the one I desire.

**Comment by just-Nob** [comment]
Anyway, out would be great to have the option to quickly go through the years by using the custom calendar / date picker, because this one enables the user to display the days being equipped with some entries.

**Comment by billthefarmer** [comment]
The reason that this app offers a choice between the custom calendar and the built in date picker is because they each offer different but useful functionality.

**Comment by just-Nob** [comment]
I guess it's not that easy to implement the advantages of the built in / system date picker into the custom one...? ;-)
