### ISSUE TITLE
"Jump to date" by tapping the headline's date

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#142]
This would be a nice alternative to the menu's command.

**Comment by billthefarmer** [comment]
This may be possible. I shall investigate.

**Comment by billthefarmer** [comment]
Good idea &ndash; but I've been here before. The id 'action_bar' needed to access the title view is an internal android id, and not accessible to applications, so I can't get a handle on it to attach an action.

**Comment by just-Nob** [comment]
I understand - it's a pity!
So I'm going to close that issue.
