### ISSUE TITLE
photo orient

### ISSUE THREAD

**Issue by HaujetZhao** [billthefarmer/diary#144]
Some photos took by phone have the orient 90 attribute, which change their orientation.

The photo shows correctly in the gallery may have wrong orientation in the **Diary**. 

![Screenshot_2020-06-20-15-42-49-798_com miui gallery](https://user-images.githubusercontent.com/19181833/85196452-e4edf180-b30c-11ea-9c69-c2504fd70af3.jpg)

![IMG_20200620_154240](https://user-images.githubusercontent.com/19181833/85196462-ec14ff80-b30c-11ea-9be7-1a93608c46fa.jpg)

![Screenshot_2020-06-20-15-43-14-603_org billthefarmer diary](https://user-images.githubusercontent.com/19181833/85196468-f20ae080-b30c-11ea-8f43-e6241a3fd24c.jpg)

**Comment by billthefarmer** [comment]
Displaying images and other media is done by the android build in [WebView](https://developer.android.com/reference/android/webkit/WebView). Obviously the version on your phone ignores the Exif orientation. The diary app itself doesn't touch the image except to copy it if you use the **Copy images** setting.
