### ISSUE TITLE
app state is lost on screen rotation 

### ISSUE THREAD

**Issue by ufarooq** [billthefarmer/diary#148]
version: 1.5
Open the app, open an existing note, click edit and restart the activity by rotating, editing mode is lost and the app goes back to view mode.

**Comment by billthefarmer** [comment]
Can't reproduce that...

![Screenshot_20200830-100036 1](https://user-images.githubusercontent.com/3448386/91655347-d871dc00-eaa7-11ea-97c5-ffc1b597b79e.png)

![Screenshot_20200830-100053 1](https://user-images.githubusercontent.com/3448386/91655368-f50e1400-eaa7-11ea-973f-cda545080843.png)
