### ISSUE TITLE
Global dark mode

### ISSUE THREAD

**Issue by TechnologyClassroom** [billthefarmer/diary#149]
The dark mode for editing is great!  Dark mode for everything would be better.

**Comment by billthefarmer** [comment]
You can have any colour scheme you like, just update the style file here &ndash; https://github.com/billthefarmer/diary/issues/106#issuecomment-529879697.

**Comment by TechnologyClassroom** [comment]
I can modify CSS and I will being doing that, but for regular people a switch in the UI would be helpful like we have for turning the editor into dark mode.

**Comment by billthefarmer** [comment]
That is not really feasible without disrupting the facility for custom styles.
