### ISSUE TITLE
Feature Request: Add a setting to choose the location for the files' directory

### ISSUE THREAD

**Issue by doronbehar** [billthefarmer/diary#15]
What do you think?

**Comment by billthefarmer** [comment]
It appears to be a widely used convention that if android apps use storage, they use a folder that can be identified with the app. For instance on my phone Aldiko uses eBooks, MAPS.ME uses MapsWithMe (it used to be called Maps with Me), Navigon uses Navigon, SoundRecorder uses SoundRecorder, etc.

So Diary uses Diary, so everyone knows what that folder is and won't delete it by mistake.

**Comment by doronbehar** [comment]
You are right but it doesn't mean users shouldn't at least have the choice to change it's location. Of course the default location should stay as it is but this idea came to me because I use [syncthing](https://syncthing.net/) to synchronize some of the directories on my device. Here's my setup:

I sync `/sdcard/documents` to `~/documents` on my computer and I would have liked to sync `/sdcard/diary` to `~/documents` on my computer but this configuration is referred to as ['nested sync pairs'](https://docs.syncthing.net/users/faq.html#am-i-able-to-use-nested-syncthing-folders) on syncthing's documentation which is a considered unrecommended and unsupported.

I could have avoid another sync pair if I could change the diary's directory location to `/sdcard/documents/diary`.

**Comment by billthefarmer** [comment]
Ok, I have released a new version with the option to change the storage folder.

**Comment by doronbehar** [comment]
Wow, Thank you So much!
