### ISSUE TITLE
render ascii diagrams

### ISSUE THREAD

**Issue by legrostdg** [billthefarmer/diary#152]
Thanks for diary, it's great! The only thing I'm missing compared to my written diary is the ability to draw (simple) schemas. It would be great to be able to draw ascii diagrams in editor mode, which would be rendered in reader mode. Something like https://github.com/ivanceras/svgbob integrated in diary would be great.

**Comment by billthefarmer** [comment]
Svgbob is written in rust, which I don't think is supported in android by the dev tools. The obvious way to do this would be with an external site like the one I suggest for [Latex](https://github.com/billthefarmer/diary#latex) where you can send a text string and get an svg file back. However AFAIK, there isn't one yet, but it's early days, this is alpha software. As a workaround, you can use their [Svgbob Editor](https://ivanceras.github.io/svgbob-editor/) and copy the svg into a diary entry.

![Screenshot_20201208-092257 1](https://user-images.githubusercontent.com/3448386/101465014-53645180-3937-11eb-8318-15e7195b5ade.png)

**Comment by legrostdg** [comment]
For sure, an external site can be used as a workaround. It does not provide the same user experience, though :-). I mentioned svgbob, but there are a lot of equivalents, for example http://ditaa.sourceforge.net/ (and ditaa is written in Java).

**Comment by billthefarmer** [comment]
I like to keep my apps as simple as possible by not including multiple external resources to add features of limited use. That's why maps, etc, use an external web site rather than trying to include the functionality in the app. It's a diary offering the optional use of markdown with a few extra features enabled by the web view used for display. An interactive svgbob editor is another app.

**Comment by billthefarmer** [comment]
I've raised an issue https://github.com/ivanceras/svgbob/issues/70 suggesting that they provide a text2svg page.
