### ISSUE TITLE
Please support webdav backup

### ISSUE THREAD

**Issue by luo-chuan** [billthefarmer/diary#154]
As the title. Please add webdav support.

**Comment by billthefarmer** [comment]
A webdav client is another app. There are some on the play store, but not on f-droid that I could see. Any app that can copy or synchronise a folder to another device or server can do the job. I mention [Syncthing](https://syncthing.net) in the help file and README, that works well.

**Comment by luo-chuan** [comment]
> A webdav client is another app. There are some on the play store, but not on f-droid that I could see. Any app that can copy or synchronise a folder to another device or server can do the job. I mention [Syncthing](https://syncthing.net) in the help file and README, that works well.

Thanks for your answer.
