### ISSUE TITLE
add support for code blocks

### ISSUE THREAD

**Issue by legrostdg** [billthefarmer/diary#155]
It seems like it is not possible to use code blocks with '''. One could still use four spaces at the start of each line, but it is not very user friendly for a lot of code lines. It would also be nice to use a monospaced font for this.

**Comment by billthefarmer** [comment]
The markdown library that this app uses supports the original [Markdown](https://daringfireball.net/projects/markdown/syntax) syntax, which doesn't support the extensions which were subsequently added by various implementations. It's a diary, not a code editor.

**Comment by legrostdg** [comment]
Again, I did not want to replace a code editor. These are called "code blocks" but they are more like "escaped blocks". For example, one can copy-paste a note from a random website and easily preserve the formatting with '''. Escaping each line in this context is boring and error-prone.

**Comment by legrostdg** [comment]
Would switching to a standard-defined markdown library be feasible? I think commonmark is the de-facto standard, it has a java implementation https://github.com/commonmark/commonmark-java and is (supposed to be) unambiguous, which is not the case for the original markdown https://spec.commonmark.org/0.29/#why-is-a-spec-needed-

**Comment by billthefarmer** [comment]
I have pushed a new version which uses an updated version of the [MarkdownView](https://github.com/billthefarmer/MarkdownView) library, which I have updated to use commonmark.

**Comment by legrostdg** [comment]
Great, thanks!
