### ISSUE TITLE
Fetch events from multiple calendars

### ISSUE THREAD

**Issue by umazalakain** [billthefarmer/diary#157]
I have no idea how doable this is or whether it would seveely complicate the app (I love its simplicity), but it would be nice if the "Add events" action could add events from all the calendars on the system. Ideally there could be a setting to explicitly select which ones to include, but maybe it's too much work.

Anyway, thanks for this wonderful app, I'm managing to keep a diary for the first time ever and I love it, especially the rendering with custom CSS.

**Comment by billthefarmer** [comment]
I didn't think of that when I added this function, it just gets events from the first calendar, which is the one it puts events in, if you use that function. I can make it insert all events, but it may pick up things like holidays and contact's birthdays if they're in there. For example, if you go to 1st March, you get
```
 @00:00 St. David's Day (Wales)
```
If you go to the Calendar app and turn off sync for the Holidays calendar, it doesn't appear.

**Comment by umazalakain** [comment]
That would be amazing, and I think it's a good compromise, plus it's always easier to manually delete events than to add them.

**Comment by billthefarmer** [comment]
OK, I've pushed a new version which gets events from all calendars. F-Droid is a bit slow at the moment, they haven't yet built the previous version of this app.

**Comment by umazalakain** [comment]
Woah thanks a lot, I can't wait to install it!
