### ISSUE TITLE
Recurring events are not added

### ISSUE THREAD

**Issue by umazalakain** [billthefarmer/diary#158]
I built the latest version of Diary on NixOS (bit of an ordeal) to try adding events fro multiple calendar, which works well. However I am not sure whether it is as a consequence of this last change or if it was like this before too, but recurring events are not shown. I don't know if it's possible to ask the calendar provider to compute all the events for a particular day for us, or if it's the calendar app that does that, in which case it's probably not worth taking it any further.

**Comment by billthefarmer** [comment]
Looking at the calendar app, recurring events are set on the first instance of the event. So, if you pick that day in the Diary app, you should get the event, but only for that day because everything is ignored except the start time and title. I assume the calendar app fills in recurring events.

**Comment by umazalakain** [comment]
I think it might be possible to get the calendar provider to compute the occurrences by using the read only `CalendarContract.Instances` instead of `CalendarContract.Events`?
https://developer.android.com/reference/android/provider/CalendarContract.Instances

**Comment by umazalakain** [comment]
Working on a PR, but it might take me a bit, I'm new to Android development
