### ISSUE TITLE
Wishlist: act as target to share/send links/text etc 

### ISSUE THREAD

**Issue by rgh36167** [billthefarmer/diary#16]
It would be very handy if Diary could receive shared links, text snippets and maybe more.

Text snippets shared from Firefox also have the URL of the webpage they are coming from, this would make the app perfect to archive important snippets from webpages visited.

The inserted text could be indented by default.

**Comment by billthefarmer** [comment]
I will investigate. I assume what you mean by a snippet is some selected text on a web page. I just tried it with an image from a web page, which worked, but when you quit the web browser you get a broken link because it's just a temporary copy. If you also get a link to the original image I could use that instead.

    ![20131726.jpg](file:///storage/emulated/0/Android/data/org.mozilla.firefox/files/temp/20131726.jpg)

**Comment by rgh36167** [comment]
Yes, I  meant text pieces selected and copied from web pages. The images would also be handy when I think about it. 

Thought also about some kind of web page archiving but do not know of an easy way to save a webapge with all dependencies so getting the text snippets and links seems to be the best option short term.

Possibly a link could be also passed to termux where some custom script could do anything with it (youtube-dl, w3m -dump,.. ) and pass the results back to Diary but don't have a real use for this at the moment.

**Comment by billthefarmer** [comment]
Looks like you just get the text, no URL. But the sent text works fine, you just can't tell where it came from.

    09-16 16:23:12.424   447  6655 I ActivityManager: START u0 {act=android.intent.action.SEND typ=text/plain flg=0xb080001 cmp=org.billthefarmer.diary/.Diary clip={text/plain T:Currency} (has extras)} from uid 10082 on display 0
    09-16 16:23:13.454   447  1267 I ActivityManager: START u0 {cmp=org.billthefarmer.diary/.DiaryCalendar (has extras)} from uid 10161 on display 0
    09-16 16:23:14.010   447   469 I ActivityManager: Displayed org.billthefarmer.diary/.DiaryCalendar: +497ms (total +1s538ms)
    09-16 16:23:26.495  3900  3900 D Diary   : Intent Intent { act=android.intent.action.SEND typ=text/plain flg=0x1b080001 cmp=org.billthefarmer.diary/.Diary clip={text/plain T:Currency} (has extras) }
    09-16 16:23:26.496  3900  3900 D Diary   : Uri null

Firefox does send an URL with an image in the clip. I shall look at that with a view to substituting it if the image is in an app's folder under `Android/data`.

**Comment by billthefarmer** [comment]
I have released a new version that will accept text shared from another app. But no URL. It will also attempt to get a web URL from shared images.

**Comment by rgh36167** [comment]
thanks. I mixed it up, the URL is shared only when I share a complete webpage from the main menu/share option.

As of the images, it might be better and certainly easier to simply copy them. Things on the internet disappear fast, especially the more interesting ones.

**Comment by billthefarmer** [comment]
I didn't want to get into copying images, especially as the files can be large.

**Comment by rgh36167** [comment]
When sharing a link (from the three dot menu/share) you can get the page title as well. Could you pleas add this?

intent:#Intent;action=android.intent.action.SEND;type=text/plain;launchFlags=0x1
0080000;B.org.mozilla.firefox.intent.extra.DEVICES_ONLY=true;S.android.intent.ex
tra.SUBJECT=Effects%20of%20bromocriptine%20on%20plasma%20catecholamines%20in%20n
ormal%20men.%20-%20PubMed%20-%20NCBI;S.android.intent.extra.TEXT=https%3A%2F%2Fw
ww.ncbi.nlm.nih.gov%2Fpubmed%2F460538;S.android.intent.extra.TITLE=Effects%20of%
20bromocriptine%20on%20plasma%20catecholamines%20in%20normal%20men.%20-%20PubMed
%20-%20NCBI;end

**Comment by billthefarmer** [comment]
I assume you would want the title as the alt text instead of the name like this

    ![Title](<url>)

**Comment by rgh36167** [comment]
I use "Intent Intercept" from f-droid to catch intents:)

Seeing both the title and url would be useful in some situations.

**Comment by billthefarmer** [comment]
Ok, that will be in the next version. If there is no title the title will be the the last part of the url, which is either the file name or the page name. There will also be the ability to request and receive media, see #20.
