### ISSUE TITLE
Markdown tables

### ISSUE THREAD

**Issue by Agne-Mathetes** [billthefarmer/diary#160]
Hi!
Here is a feature request:
* implement markdown tables:

https://www.muo.com/tag/create-markdown-table/

This would be very helpful, since I often use this in other editors.

**Comment by billthefarmer** [comment]
I have released a new version with tables and task lists

**Comment by Agne-Mathetes** [comment]
Thank you very much Sir!

Sincerely / Uppriktigt,
Agne Mathetes

📬 PR, 701 00 Örebro, Sweden 🇸🇪
☎️ [+46733912575](tel:+46733912575)

[LORD_of_glory.jpg]

Sent from ProtonMail mobile

-------- Originalmeddelande --------
På 8 feb. 2021 15:31, Bill Farmer skrev:

**Comment by Agne-Mathetes** [comment]
> I have released a new version with tables and task lists

One question: How do I best compile this source code into an APK on an Android phone? I have Termux with GCC installed. I don't own any other computer.

**Comment by billthefarmer** [comment]
The easiest way to build it from a phone would be to let Github do it for you online. You would have to fork this repository, add some code to the build workflow, `build.yml`, to create an upload artefact and download it. By the time you have worked out how to do that and got it working, [F-Droid](https://f-droid.org/packages/org.billthefarmer.diary/) will have got around to building the latest version and you can get it from there. They have been very slow this time.
