### ISSUE TITLE
Umlaut

### ISSUE THREAD

**Issue by Bukbi** [billthefarmer/diary#161]
Hey there, 
with the latest update, I noticed that some of my styles wouldn't work anymore. I figured out that this was due to my use of an umlaut in one if them. 
Thanks a lot for the app!

**Comment by billthefarmer** [comment]
The only significant changes I have made is the switch the markdown view to Commonmark, so I could add code fences, tables and task lists. The styles never get anywhere near the markdown, but the [Android System WebView app](https://play.google.com/store/apps/details?id=com.google.android.webview) gets updated from time to time. There is an item in the developer options to choose webview. If there is something unrecognised in the styles it usually gets ignored.
