### ISSUE TITLE
(Feature Request) An app lock for the Diary app

### ISSUE THREAD

**Issue by shouyou10** [billthefarmer/diary#162]
If someone keeps record of his daily life in the diary app and passes his phone to another person and that person opens the diary app; it becomes a mess. To avoid such a scenario an app lock can come really handy. Will it be possible to make the addition to this amazing 'Diary' app?

**Comment by billthefarmer** [comment]
There are several ways to deal with this - Don't put the app on your launcher screens. Put the app in a folder with a misleading name. Use launcher functionality to hide/lock/protect apps if available. Use an applocker app, there are several on F-Droid - https://search.f-droid.org/?q=app+lock&lang=en. All these are generic, you can use them for any app.
