### ISSUE TITLE
keep displaying date when using search

### ISSUE THREAD

**Issue by legrostdg** [billthefarmer/diary#165]
When using search, the date is hidden by the "search bar". It is not optimal, especially when using "find all". It would be nice to have the date being displayed somewhere.

**Comment by billthefarmer** [comment]
This is standard android functionality, the search bar temporarily takes over the toolbar. On a small phone there isn't a lot of real estate to put another copy of the app title which in this case is the date of the current entry. And it would have to be hidden when not in use. In landscape you can't see the current entry at all.

![Screenshot_20210423-140844 1](https://user-images.githubusercontent.com/3448386/115885225-a6065c00-a447-11eb-926b-717f618b2946.png)
