### ISSUE TITLE
Display day of the week in title

### ISSUE THREAD

**Issue by rahqbo** [billthefarmer/diary#166]
When swiping through my last entries, after some days I find it difficult to assign weekdays to the day of the month. A little addition to the title would help me a lot.

Thank you for the app.

![Diary-phone](https://user-images.githubusercontent.com/34191162/116663531-84e9c200-a997-11eb-807f-125e177cc99f.png)

**Comment by billthefarmer** [comment]
The date format of the title is selected to ensure it will fit on smaller devices. In landscape and on larger devices you get the full date.

![Screenshot_20210430-095528 1](https://user-images.githubusercontent.com/3448386/116684212-97b8c280-a9a8-11eb-807f-2e89b937c12d.png)

**Comment by rahqbo** [comment]
Thank you for the help, I did not know that. Is it possible to add a toggle in the settings that enables the widescreen date format for horizontal mode? That would make me really happy.

**Comment by citizen2947294** [comment]
Does it not show the weekday when you orient your screen horizontally/in landscape? It does for me.

**Comment by billthefarmer** [comment]
Also it is necessary to leave room for the back arrow for back navigation.

![Screenshot_20210502-153432 1](https://user-images.githubusercontent.com/3448386/116816941-0d18c480-ab5c-11eb-8127-d61b5b369e56.png)
