### ISSUE TITLE
Add front matter extension to markdownview

### ISSUE THREAD

**Issue by bayang** [billthefarmer/diary#167]
I just saw that you recently switched to commonmark for markdown parsing in your Markdownview.

Would you accept to add the commonmark-ext-yaml-front-matter extension to it in addition to TablesExtension and TaskListItemsExtension ?

I use front matter to store some metadata in my markdown files, actually the front matter content is rendered in the html view which is not wanted.

This extension makes the parser aware of the metadata and it is not displayed.

I don't think this would have an impact on people not using it.

And maybe, who knows, you would find a use case in Diary where storing some metadata in the front matter would be useful.

**Comment by billthefarmer** [comment]
OK, the next version will have that plus autolink.

**Comment by bayang** [comment]
Nice ! 

Thank you very much !

**Comment by midaspt** [comment]
After checking the relevant **CommonMark** spec (cf. <https://spec.commonmark.org/0.30/#thematic-breaks>) and searching the net at large, I had trouble finding anything that would support the change in treatment of horizontal line `---` (see **#179** above) to denote "_front matter_" instead...

Apart from many programmatic solutions to extend markdown to accommodate such needs, the only official reference I could summon says the following:

> _Front matter is not going to be part of the spec_. An application that uses **CommonMark** can employ its own conventions for extracting lines from the front of the document and parsing them as front matter. In general, the needs will be different for different applications.
> <https://talk.commonmark.org/t/front-matter-best-practice/2235>

Thus, I request the change be reverted as it is not part of the **CommonMark** standard.

**Comment by billthefarmer** [comment]
The [YAML front matter](https://github.com/commonmark/commonmark-java#yaml-front-matter) extension is part of the [commonmark-java](https://github.com/commonmark/commonmark-java) implementation. I will not be removing it.

**Comment by midaspt** [comment]
I see. [commonmark-java](https://github.com/commonmark/commonmark-java) is a "_Java library for parsing and rendering CommonMark_".

This may seem a minute issue but it breaks compliance with the **CommonMark** spec, as noted above, and there's no telling where else it happens -- **Diary** can't really claim to observe the standard anymore.

**Comment by billthefarmer** [comment]
It's a diary, not a standards compliance test platform. A quick ~~Google~~ Ducky reveals YAML front matter extensions for various implementations of commonmark. If someone comes up with a suggestion that's a good idea, if possible, it goes in the app.

**Comment by midaspt** [comment]
I beg to differ: I an user can't be certain a so called standard-based application effectively adheres to the prominent standard, then his data will be forever in jeopardy -- as my own case broadly illustrates.

But, hey, your app, your rules -- I just wish that somehow I was aware of this before committing years of my data.

**Comment by bayang** [comment]
Or maybe you could just use 4 dashes instead of 3 as suggested, or use stars instead of dashes and be done with it ?

You could also try other apps or editors but I'm afraid you're likely to face the same problem since yaml frontmatter and markdown extensions are litterally everywhere these days.
