### ISSUE TITLE
Provide config to disable coordinates replacement regex

### ISSUE THREAD

**Issue by bayang** [billthefarmer/diary#170]
Hi, 
would it be possible to add an option in config to disable the coordinates replacement by regular expression ?

If I understand correctly I think it happens in the mapCheck method in Diary.java with the MAP_PATTERN regex.

I still want osm coordinates formatted like this `![osm](geo:48.71143,4.1492)` to be displayed though.

So I think in the end it could look like this : 

```java
// markdownCheck    
private String markdownCheck(CharSequence text)   
 {        
    // Date check        
    text = dateCheck(text);
    // Check for map
    if (configShouldCheckMap) { // <-- optionally disable replacement
        text = mapCheck(text);
    }
    // Check for media        
    return mediaCheck(text).toString(); // <--- but still render osm formatted tags as OSM maps
}
```

**Comment by billthefarmer** [comment]
That's not going to work. The reason for preprocessing markdown in the diary app is so that non-standard-ish markdown such as video and maps will appear correctly in the markdown view that displays the entry. The markdown view only handles standard markdown plus some enhancements by using commonmark. If you leave the coordinates as they are they will display as an image.

![osm](geo:48.71143,4.1492) (`![osm](geo:48.71143,4.1492)`)

**Comment by bayang** [comment]
Hmmm,

I thought that the mapCheck method's only job in markdownCheck was to replace coordinates-like string with  `GEO_TEMPLATE = "![osm](geo:%f,%f)";`

And that there was a second pass of markdown preprocessing in the mediaCheck method, where patterns like `[osm](geo:%f,%f)`   (produced by the addMap method after intent import and by mapChek method seen above) were replaced by the 
`MAP_TEMPLATE =        "&lt;iframe width=\"560\" height=\"420\" " +        "src=\"https://www.openstreetmap.org/export/embed.html?" +        "bbox=%f,%f,%f,%f&amp;amp;layer=mapnik\"&gt;" +        "&lt;/iframe&gt;&lt;br/&gt;&lt;small&gt;" +        "&lt;a href=\"https://www.openstreetmap.org/#map=16/%f/%f\"&gt;" +        "View Larger Map&lt;/a&gt;&lt;/small&gt;\n";`

So I thought that skipping the mapCheck method would prevent replacement of coordinates but would still lead to my lines like `![osm](geo:47.71143,4.1492)` to be replaced with the openstreetmap iframe in the mediaCheck method.

Because at the moment, if I enter something like this in my diary : 

`Today I found a cache whose coordinates were [3.149200,50.711430]`


I end up with : 

`Today I found a cache whose coordinates were ![osm](3.149200,50.711430)`

**Comment by billthefarmer** [comment]
Ah, I misinterpreted what you meant. This code is in the app as a result of a much earlier comment #27, which suggested the syntax `[<lat>,<lng>]`. I later changed it to the geo Uri syntax, as a result of later comments, but left the code in for compatibility. You can stop it happening by using different brackets, or putting `[<anything other than osm>:<lat,<lng>]`.

**Comment by bayang** [comment]
Ok, I 'll try your suggestion.

Thank you for your answer
