### ISSUE TITLE
Add toolbar for the editor

### ISSUE THREAD

**Issue by DhruvaSambrani** [billthefarmer/diary#172]
A simple toolbar, especially for the more non-standard features, such as events and dates would facilitate better use of them in the app.

**Comment by billthefarmer** [comment]
I'm a bit puzzled as to what you mean by that. There are already three toolbars on an android phone &ndash; the phone toolbar, the app toolbar and the navigation bar. Where would you put another one and why?

![Screenshot_20210630-082335 1](https://user-images.githubusercontent.com/3448386/123919232-a60d6580-d97c-11eb-9f33-311c499e8fbc.png)

**Comment by DhruvaSambrani** [comment]
Ah sorry, let me clarify

I meant a toolbar in the editor, with a button for adding an image, or an event. We could also add buttons for Bold and stuff, but people using diary will probably know basic md syntax.

I looked at the code, it seems easy enough to add a tool bar under the edit area, but we need to decide on which features to add to it.

Or, we could completely overhaul the editor, and use an android markdown editor library, or make another webview which runs one of the many html-based markdown editors.

**Comment by billthefarmer** [comment]
All the functionality of this app is within easy reach, either in the toolbar, the edit/accept button or the menu. Adding another toolbar is using up valuable real estate, especially on a small phone,  for no real gain.
