### ISSUE TITLE
Print/Share date [dd.mm.yyyy-dd.mm.yyyy] (and add export to pdf/xxx?)

### ISSUE THREAD

**Issue by natrius** [billthefarmer/diary#176]
I'm using the app mainly to write travel diaries and it would be nice to be able to export/print/share from date x to date y to html to send it someone.  That could work with just 'print to pdf' or something as well, but its not possible to select multiple days while printing, just the current page. Share also just selects the current day. 

On desktop there is something like https://pandoc.org/ to achieve something, as far as i'm aware.

**Comment by billthefarmer** [comment]
The android printing function the app uses is built into the web view that displays the formatted view. The app can only handle one diary entry at once, so printing more than one entry at once is unlikely. The same applies to sharing. Pandoc appears to be a windows/macos/linux application written in Haskell, exceedingly unlikely to port to android.

**Comment by billthefarmer** [comment]
It is possible to use my [Notes](https://f-droid.org/packages/org.billthefarmer.notes/) app to consolidate several diary entries by copying and pasting, and then printing the result. Unfortunately neither markdown or HTML have a concept of page breaks, AFAIK, and multiple blank lines are ignored, so the page breaks are unfortunate. This is just test entries from my diary. You could do it in the diary, but that would get saved automatically.

[Notes_Document[1].pdf](https://github.com/billthefarmer/diary/files/6998977/Notes_Document.1.pdf)

**Comment by natrius** [comment]
An idea: 

***Current behaviour***

- press three dots
- select 'Share'
- select app and person
- a in-app-screenshot is shared, including the edit-button and the three dots above an left/right arrow

***Desired behaviour***

- press three dots
- select `Share`
- select Dates `from` and `to` (default just this date selected?)
- Select app and person
- Diary creates a temporary entry
- Diary copies all selected dates into the temporary entry including the date on top
- Create screenshot inapp from just the entry without top navigations and without edit-button

This way there is no page break is needed. And it would be able to create an html to share with somebody as well.

**Comment by billthefarmer** [comment]
Obligatory XKCD https://xkcd.com/1425/.

**Comment by billthefarmer** [comment]
I have done some investigation into this. It is not possible to get a web view to render an image larger than what is on screen, AFAICT. It's possible to create an image the size of the actual diary entry but only the part visible on screen gets rendered. Also, concatenating several diary entries would generate, if it were possible, an image with a ridiculous aspect ratio, many times taller than it is wide. It's possible to change the image generated to just the diary entry without the toolbars.

Here's an example, the lower part is transparent, so you can't see anything.  :shipit:

![Notes](https://user-images.githubusercontent.com/3448386/129899972-fb5f43ea-929a-475e-afb9-2ea3726b3ab8.png)
