### ISSUE TITLE
Images gets added in reverse order

### ISSUE THREAD

**Issue by Hund** [billthefarmer/diary#178]
When you select multiple images from the image gallery, they get added in reverse order.

I'm currently using Diary 1.81 from F-Droid on my Pixel 3a with Android 12. The bug has been present on Android 11 and on previous versions of the application for as long as I can remember. :)

**Comment by billthefarmer** [comment]
In the diary app, images are added in the order they appear in the list send by the gallery app. I just tested this &ndash; It's not possible to select more than one image in the gallery when using **Add media** on either of the devices I tried. If I share more than one image from the gallery on a Moto phone running android 7, they are added in the order they appear in the gallery, regardless of which order they were selected in. If I do the same thing on a Samsung tablet running android 11, they are added in the order they were selected. The code that iterates through the list of images is very simple, it is [here](https://github.com/billthefarmer/diary/blob/7af39975d987c7a30cb240e4aa38204f63089276/src/main/java/org/billthefarmer/diary/Diary.java#L1513).

**Comment by Hund** [comment]
So. You're not going to fix this issue?

**Comment by billthefarmer** [comment]
I explained what happens when I tested above. What am I supposed to fix, your image gallery?

**Comment by Hund** [comment]
> I explained what happens when I tested above. What am I supposed to fix, your image gallery?

I understand that you can't do that, but what you can do is to make the importing of images better in your application.

An improvement would be for the user to be able to import more than one image.

Another quality of life improvement, which is semi-OT, here is the ability to delete images from the diary library.

**Comment by billthefarmer** [comment]
I have tested importing multiple images. Three different apps returned three different results making designing a foolproof implementation somewhat problematical.
