### ISSUE TITLE
The "Save" button takes too much space

### ISSUE THREAD

**Issue by cicithesquirrel** [billthefarmer/diary#18]
On my 4.7" display, the "Save" button hides the end of the last lines:
![screenshot](https://user-images.githubusercontent.com/8672995/30530058-cf1596ac-9c43-11e7-93cc-f8da544d9172.jpeg)

I cannot read the words behind, nor place the cursor on them.

At first I liked this nice blue button, easily accessible. But now, I must say I'd rather have an simple icon in the window black toolbar. Unless it could be technically possible to scroll beyond the end of the text, so that the last lines *appear* above the button?

**Comment by billthefarmer** [comment]
The solution is to enter some blank lines at the end of the text so that it will scroll up. They won't show in the markdown view. If you can't get the cursor there, temporarily turn off markdown mode so the button doesn't show.

![screenshot_20170918-100736](https://user-images.githubusercontent.com/3448386/30535239-82f42f48-9c59-11e7-8c9b-cbfeef4708a0.png)

The reasons for the button being there is so that it doesn't use up space on the toolbar on small devices and having an important part of the UI there is part of the android style guide.

**Comment by cicithesquirrel** [comment]
Ok. But in fact there is the same problem when viewing an entry: the "edit" button may hide some text. What do you think?

**Comment by billthefarmer** [comment]
It's not enough of an issue to justify changing the design of the app. The standard android email app, calendar app and GMail app have a button in the same place that obscures text. See the [android design docs](https://material.io/guidelines/components/buttons-floating-action-button.html).

**Comment by billthefarmer** [comment]
Ok, a long touch on the button will hide it, a long touch on the page will restore it. That will be in the next version.

**Comment by cicithesquirrel** [comment]
Ok, that's an idea. Or maybe an option in the app parameters to move the Edit button in the toolbar instead of the previous/next button? I guess this is more complicated!
Or... I just found that the Yahoo Mail app adds a little bit of transparency on the main button background. Maybe this could be enough and easier to implement. Just my two pence...

**Comment by cicithesquirrel** [comment]
You may wish to have a look to "Firefox Focus". There is a floating "Clear" button that disappears when scrolling down and reappears when scrolling up.

**Comment by billthefarmer** [comment]
I hadn't noticed that. It's the wrong way round for this app, if you can scroll something up to read it you don't need the button to disappear. Also it would be annoying if you are editing something at the bottom of a long page and you have to scroll up to get the button to see what it looks like. I will investigate.

**Comment by billthefarmer** [comment]
Well I tried it, it's only possible for the markdown view, because the API for a scroll view isn't implemented until android 23, and I'm supporting android 14. I still think it's annoying.

[Diary-debug.zip](https://github.com/billthefarmer/diary/files/1362624/Diary-debug.zip)
