### ISSUE TITLE
Preview button never disappears and are in the way of the text

### ISSUE THREAD

**Issue by Hund** [billthefarmer/diary#181]
Preview button never disappears and are in the way of the text. It should automatically guide itself when you start writing.

![IMG_20211212_080730](https://user-images.githubusercontent.com/320498/145703723-657d6cdf-8b84-4c83-a6cf-1c5ffe95ae62.jpg)

I'm currently using version 1.82 from F-Droid on my Pixel 3a. This has always been an issue for as long as I've been using this application.

**Comment by billthefarmer** [comment]
There have been various issues raised about this button. It it part of the Material style guide and appears in many other apps. It is translucent so you can read text through it, as in your screenshot and can be temporarily removed. See Editing and Scrolling in the README.Sent from my Galaxy

**Comment by Hund** [comment]
Thanks! I didn't know it was possible to hide it.
