### ISSUE TITLE
[Feature request] Adaptive icon

### ISSUE THREAD

**Issue by Hund** [billthefarmer/diary#182]
Adaptive icons was introduced 4 years ago. Have you considered following the style guidelines that Google have and adding support for it?

**Comment by billthefarmer** [comment]
I find this quite amusing, it appears to be a case of do as I say, not as I do. None of Chrome, Earth, Google, Maps, News, Play, or St View appear to have adaptive icons, AFAICT. One the advantages of free and open source development is that you can do functionality over form, and ignore the constantly moving goalposts.Sent from my Galaxy

**Comment by Hund** [comment]
So.. Just because Google are inconsistent, you're not going follow the guidelines and let your application be the awkward outcast on everyones launcher?
