### ISSUE TITLE
skip dates using the custom calendar

### ISSUE THREAD

**Issue by neil-edelman** [billthefarmer/diary#184]
There is no way to skip years using the custom calendar like the standard datePicker.

![Screenshot_20220110-224653_Diary](https://user-images.githubusercontent.com/774033/148851987-2e79a958-db48-43d1-8b0b-c6933577a119.png)

**Comment by billthefarmer** [comment]
RTFRM &ndash; swipe up and down in the custom calendar as per the [README](https://github.com/billthefarmer/diary#swipe-up-and-down) and also in the [help file](https://github.com/billthefarmer/diary/blob/master/data/help.md#swipe-up-and-down) that gets loaded when you first use the app.
