### ISSUE TITLE
home screen widget

### ISSUE THREAD

**Issue by alehresmann** [billthefarmer/diary#186]
Hi,

Would it be possible to add the ability to create a widget on the homescreen, where one can see the diary entry for the current day?

Thanks for your consideration.

**Comment by billthefarmer** [comment]
I will investigate.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

![Screenshot_20220214-130918 1](https://user-images.githubusercontent.com/3448386/153870504-e2d94a50-8da8-4749-a6ed-099e8853995a.png)

**Comment by alehresmann** [comment]
Thank you very much!
