### ISSUE TITLE
[Request] Support for HEIC-images

### ISSUE THREAD

**Issue by Hund** [billthefarmer/diary#187]
It would be nice with support for HEIC-images. It's the default image format used by Apple.

It's common (at least for me) to use images that gets sent to me in my dairy. These images often happens to be HEIC-images. The only issue is that Diary can't preview them.

**Comment by billthefarmer** [comment]
Diary uses the android [WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) to display content. Android supports the HEIC format from android 10, but I think that just means JPEG files using HEIC compression. Two devices I tested running android 11 recognise .heic files as images, but can't display them.

**Comment by Hund** [comment]
Oh. I guess I have to look into some tool to convert them then. :)
