### ISSUE TITLE
WebView content refreshes after device orientation change

### ISSUE THREAD

**Issue by mmc20520** [billthefarmer/diary#188]
Hi, would you be able to restore webview states when screen orientation change?

For example, this is what is displayed before rotation:
<img width="300" alt="Screen Shot 2022-03-03 at 7 39 04 PM" src="https://user-images.githubusercontent.com/100833575/156558068-1ee3b14b-f621-4b6e-9dd5-abecec5cb4a2.png">

After rotation, the content is refreshed and I have to manually repeat some steps to restore the content
<img width="637" alt="Screen Shot 2022-03-03 at 7 39 20 PM" src="https://user-images.githubusercontent.com/100833575/156558239-f044110e-b257-4b81-b23d-355e5b32eae6.png">

I was testing v1.84 on Android 10

**Comment by billthefarmer** [comment]
It's a diary, not a web browser. If you want web browser functionality, use an external browser. See #146.
