### ISSUE TITLE
Templates like in the notes app

### ISSUE THREAD

**Issue by AlexD97** [billthefarmer/diary#189]
Is it possible to make templates like in the notes app where dates are available (e.g. <<date YYYY MM dd>>)? 

Also, what it be possible to add (also like in the notes app) the opportunity to add the date in the menu?

**Comment by billthefarmer** [comment]
Yes, that is possible. The reason for a time in the menu is that is was requested, and the date is on view in the toolbar.

**Comment by AlexD97** [comment]
Okay, unfortunately the dates don't work in my template. 

I think it would be helpful if one can also insert the date, e.g. if one wants to use the file elsewhere.
