### ISSUE TITLE
Template is only copied when using markdown

### ISSUE THREAD

**Issue by AlexD97** [billthefarmer/diary#190]
When using markdown there is this edit button in the lower right corner. When clicking on it, the template gets inserted.
When not using markdown, there is no edit button and (therefore?) the template isn't inserted.

**Comment by billthefarmer** [comment]
If you don't use markdown the app has no way to telling, when you navigate to an entry, whether you intend to edit the entry or are just looking. If not for this it would be easy to fill the diary with empty template pages just by swiping through the entries. See #143.

**Comment by AlexD97** [comment]
But wouldn't it be better if there were also the edit/confirm button in txt-mode?
