### ISSUE TITLE
Show context of findall result items

### ISSUE THREAD

**Issue by chris-ca** [billthefarmer/diary#192]
When searching for a string in the whole diary using "find all", the result list currently always shows the date and the first 20 characters of each page. Often the beginning of a page is unrelated to the search term (or it might even be the same for all search results, e.g. when using a template).

Instead, a better search result would show the context for each item, e.g. the surrounding [n] words or lines.

**Comment by billthefarmer** [comment]
OK, that will be in the next version...

![Screenshot_20220728-111546 1](https://user-images.githubusercontent.com/3448386/181482779-6dc20197-f64c-4dea-9ad4-ff9ec7237736.png)
