### ISSUE TITLE
Link creator for the index page

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#194]
Writing links on the index page is not quite an easy task: One has to remember the link syntax or copy/paste and change, remember the date path, climb through several levels of the virtual keyboard for square brackets (in my case even backticks, too) and juggle the cursor to the correct position. Errors are not allowed, and how easy is a semicolon mistaken for a colon, a comma for a dot etc.

I imagine all this could be done with a new menu item. The user selects a portion of text on the day's page that the index shall link to, then selects the menu item, and the Diary app appends (or prepends, depending on the index's sorting order) the selected text as a correctly formatted link to the index page. There might even be a template for that in the preferences (or a proper file for that objective, similar to the style and script files), with placeholders to be replaced with the date path and the link text. A `-5` at the templates last position would append to the fifth last line, a `5` would prepend to the fifth line, both in case there is certain code content already on the index page.

It would really be fun to populate the index that way, and Diary would be easier to use, even for less tech savvy folks.

**Comment by uli-on** [comment]
An example how such a template might look like in my case:
```
[`d` PlaceholderForTextCopiedFromDayEntry](<PlaceholderForDatePath>)*i*;-5
```
... where `d` is the day of month with leading zero, and `*i*` is an optical indicator for an entry with images that gets converted via CSS.

**Comment by uli-on** [comment]
Without a template (remember the less tech savvy), the link created might look like this:

```
12.08.2022: Our Visit to Venice
``` 

... the date formatted according to local/system preferences.

**Comment by billthefarmer** [comment]
Some of this is probably possible. I will investigate. Plain links on a line on their own will be concatenated together by markdown in the same way as they would in HTML. Therefore links on an index page should possibly be wrapped in a bullet list or headers.

 * 12.08.2022: Our Visit to Venice
 * 12.08.2022: Our Visit to Timbuktoo

or
#### 12.08.2022: Our Visit to Venice
#### 12.08.2022: Our Visit to Timbuktoo

**Comment by uli-on** [comment]
> Some of this is probably possible. I will investigate

Thank you, Bill :)

> Therefore links on an index page should possibly be wrapped in a bullet list or headers.

Wouldn't a `<p>` be sufficient, simply because it wouldn't have to be normalised via CSS in order to have the same font-weight and - size as those on the rest of the pages.

**Comment by billthefarmer** [comment]
OK, I have implemented this mostly using existing functionality...

## Index template
The index template defaults to `<<date>>`, which gives an entry that
looks like [Sunday 14 August 2022](#). The template uses the same
rules as the entry template date code or pattern below. Text outside
the angle brackets will be copied unchanged, text inside the angle
brackets will be interpreted as a date code or date pattern, as below.

That will be in the next version.

![Screenshot_20220814-100531 1](https://user-images.githubusercontent.com/3448386/184530056-9503817f-76a8-4ccd-9e79-f530db98b14a.png)

![Screenshot_20220814-100703 1](https://user-images.githubusercontent.com/3448386/184530154-38557cf0-9ef8-4a36-8378-b3519dd6a566.png)

![Screenshot_20220814-100910 1](https://user-images.githubusercontent.com/3448386/184530209-85706c5b-0481-4522-a26c-84cd2144b445.png)

**Comment by uli-on** [comment]
Thanks, Bill! I'm looking forward on trying this out!

**Comment by uli-on** [comment]
This package arrived today in F-Droid. Many thanks, Bill, much obliged!
