### ISSUE TITLE
Import from online services

### ISSUE THREAD

**Issue by racuna** [billthefarmer/diary#195]
I dunno if it is possible (technical, or ethical issues), but import data from some services could be a cool feature:
- last.fm: songs listened
- google fit / gadgetbridge: steps walked
- swarm: places visited 
- simkl / tvtrack: films/shows watched
- ifttt: anything else

**Comment by billthefarmer** [comment]
Some while ago I was asked to support Dropbox/Google Drive/etc storage. I investigated and found at the time that they all had different API's and couldn't/wouldn't support sharing a real storage folder. The same applies here. I haven't investigated but, I expect these all have different APIs/secret access keys etc. It's not possible for F-Droid to build apps with proprietary libraries/secret keys etc, therefore it can't be done.

But these apps/whatever should be able to share data as either text or images and the app can add shared text or images to diary entries.

**Comment by racuna** [comment]
Yeah, thanks. I managed to integrate a lot of online tracking services (weather, criticker, strava, simkl, last.fm) with dropbox using IFTTT, then with a bash script I merge them into an ~/.Diary/YYYY/MM/DD.md file which is synced with Android using syncthing.

Then, using Diary, I can manually add some text to increase context to the entries, like what3words map coordinates. tags or just free text.
