### ISSUE TITLE
Link to help.md in help.md

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#197]
Please add a link to the online raw version of help.md into help.md

That would be in favour of all those who want to keep their help file up to date periodically, so they can click, get teleported to the current, ready-to-copy version, copy, and paste into their local help file.

**Comment by billthefarmer** [comment]
I've tried that, it doesn't work very well. You can test it by putting a link in an entry `[Help](file:///android_asset/help.md)`. The file loads into the web view OK, but when you copy and paste it, the web view removes all the newlines so you get a mishmash.

**Comment by uli-on** [comment]
Thanks for puzzling out that nice workaround!

I forgot to mention I used an external editor to "convert" (like I thought at that point) the copied text. 

It took me a detour through the settings for line breaks and encodings of some of my code editors in my desire to find out why it worked elsewhere, until I found the solution was literally lying at my fingertips already and doesn't need a full-fledged code editor: "paste text only" (retranslated), from the context menu, even in Diary.

It only needed mentioning in help.md :)

**Comment by billthefarmer** [comment]
I discovered an easier way to do this... Tap on a link to the embedded help file as above to get a copy of the file into the markdown view. Rather than copying it, share it and select Diary, choose a date, and you get a clean copy in an entry.

**Comment by uli-on** [comment]
Bill, you're a tinkerer of the best sort! Thanks!
