### ISSUE TITLE
MarkDown

### ISSUE THREAD

**Issue by moshpirit** [billthefarmer/diary#2]
A highly rich format would be very appreciated. I think this app has potential, MarkDown, a material design and even maybe a reminder (for birthdays and such) and probably would be more than enough for everyone

**Comment by billthefarmer** [comment]
I like my apps to do one thing reasonably well. All devices come with a built in calendar that can do reminders, etc. There are a couple of android markdown view libraries, but that would mean a redesign of how to implement browsing and editing. The UI is meant to work like a real paper diary, you just write on the pages and saving and restoring all happens automatically.

**Comment by billthefarmer** [comment]
Having tried out a markdown library, the next version will include the option of formatting diary entries using it. I have also added a material design theme for newer devices.

**Comment by moshpirit** [comment]
Great!! Thank you so much!!

**Comment by gilcot** [comment]
Well, but it makes the app biger, very very fat (from 100 KiB to a bit more than 1.2 MiB...) 
What I liked with the original app, before fork, was the small footprint and permission (that's another point: phone identity is now requiered)

**Comment by billthefarmer** [comment]
That's because the markdown library included the android support library for no reason. I have forked it to fix some issues, the app size is now down to about 150k.

**Comment by gilcot** [comment]
Oh great! This wight loss makes this feature (md) welcome now ; and I won't switch back to old app/interface
