### ISSUE TITLE
Audio recording support?

### ISSUE THREAD

**Issue by renyuneyun** [billthefarmer/diary#20]
Hi, I'm wondering whether it would be useful to add audio recording support.

Sometimes I'm just tired of typing words and would expect to record audio as a more detailed explaination for some texts. There is also sometime that I want to add something to my diary but don't have enough time to type everything through keyboard.

It would also be useful if the audio could be marked as "temporary" and then be hightlighted or aggregrated somewhere so the user could go back and change them to texts when there is time.

**Comment by billthefarmer** [comment]
I just looked at this. It would be possible to have embedded audio or video in the diary using HTML5 syntax as there appears to be no Markdown standard. One Node.js plugin uses the same syntax as images, but that doesn't work with the Markdown library I am using, you just get a broken image.

However none of the two audio record apps on my tablet respond to a request for an audio file, or the camera for a video file, you just get a file picker for the requested file type. You would have to record the audio file and then share it, or request it from the diary app.

I will look at requesting and receiving audio and video as well as images and text files.

**Comment by billthefarmer** [comment]
Ok, requesting and receiving media files will be in the next version. So you can make a recording, add it to a diary entry and replace it later.
