### ISSUE TITLE
Alternative filename scheme

### ISSUE THREAD

**Issue by CodingFan72** [billthefarmer/diary#201]
Hi Bill,

First of all, I would like to thank you for your great program. 👍
I've been looking for something like this for a long time.

Now to my query:

I like the plain text approach and working with markdown files.
So I designed a central repository that I can access with any text editor etc.

For example with Obsidian & Co.

Since Obsidian & Co. use a different naming convention for their daily notes (`yyyy-mm-dd.md`) and the files in Dairy are named according to the scheme `dd.md`, the linking via wiki links runs in other programs to the files not so completely smoothly.

So I wanted to ask you if it would be possible for Diary to use this naming as well.

I imagine that the user can select or define the desired scheme in the settings:

````
- dd.md // default
- yyyy-mm-dd.md
- ...
````

What do you think of the approach?

**Comment by billthefarmer** [comment]
See #70, #33. The hierarchical folder structure is embedded in the code, and would require rewrite to change.
