### ISSUE TITLE
Two diaries

### ISSUE THREAD

**Issue by wrathofthomas** [billthefarmer/diary#202]
Hi Bill, I use this app literally everyday to journal and track the days I did with the month view. It has been amazingly helpful to me.
I would like to have a second daily record log for another purpose. Is it possible to add the feature to have more than one diary?
Maybe just simply switch between one or the other in the menu and then the UI treats the current diary as if its the only diary until one switches to the other diary.

Thank you very much.

**Comment by billthefarmer** [comment]
You can use the **Folder** setting to change folders or alternatively use my [Notes](https://github.com/billthefarmer/notes) app for one use case. If you use the **New note name** template with the default `<<date>>.md`  date code you will get a hierarchical folder structure similar to this app.

**Comment by wrathofthomas** [comment]
Ok, Bill. Thanks for the suggestion. I'll play around with both and see
what works best!
