### ISSUE TITLE
Image/Photo with spaces in filename not displayed

### ISSUE THREAD

**Issue by eternalbit** [billthefarmer/diary#203]
Am I lacking understanding of markdown as to how I can make this work?

I would think that spaces in filenames are generally a non issue nowadays but apparently they lead to diary not showing the referenced image.

When I open the .md file containing such a reference (to an image with spaces in the filename) in Okular on my computer, the images do show.

**Comment by billthefarmer** [comment]
There are two issues: android is a linux based system, so filenames with embedded blanks are known to cause problems; I need to see the markdown you used to see if the issue is in the commonmark library or the web view used to display the HTML generated.

**Comment by eternalbit** [comment]
Image does not show:

`![9999-99-99 99-99-99 What happened on 99.99.9999 when demand peaked to over 500 GW.png](9999-99-99 99-99-99 What happened on 99.99.9999 when demand peaked to over 500 GW.png)`

Image does show:

`![9999-99-99_99-99-99_What_happened_on_99.99.9999_when_demand_peaked_to_over_500_GW.png](9999-99-99_99-99-99_What_happened_on_99.99.9999_when_demand_peaked_to_over_500_GW.png)`

**Comment by billthefarmer** [comment]
If you add an image using **Add media**, or by sharing the URL will have blanks replaced by `%20`. If you replace the `%20` with a blank you get the behaviour you describe. The URL in a markdown link should be a valid URL. URLs with embedded blanks are invalid, AFAIK.

```markdown
![signal 2020-12-25-085642.jpg](file:///storage/emulated/0/Pictures/signal 2020-12-25-085642.jpg)

![signal 2020-12-25-085642.jpg](file:///storage/emulated/0/Pictures/signal%202020-12-25-085642.jpg)
```

**Comment by eternalbit** [comment]
I just tried out both.

Neither with **Add media...** from within diary app itself, nor through sharing the image to diary app from another app (com.simplemobiletools.gallery.pro) are blanks in the filename replaced with `%20`s.

When I manually replace all blanks with `%20`s (in the URL in the md file) diary does indeed display the image with blanks in the filename.

Maybe the reason is the oldish Android version I'm using 🙈.

I'm aware it's only a minor issue if any at all, as most other users will probably not have this problem, so I guess I'll live with it and we can close this.

Thanks for your help :)
