### ISSUE TITLE
No strikethrough

### ISSUE THREAD

**Issue by Chick2D** [billthefarmer/diary#205]
Tried `~text~` and `~~text~~` didn't work

**Comment by billthefarmer** [comment]
I can't reproduce that, version 1.95.

![Screenshot_20221116-115948 1](https://user-images.githubusercontent.com/3448386/202175545-0d9ef471-d1db-4cc7-9e88-0a947feab4ae.png)

![Screenshot_20221116-115916 1](https://user-images.githubusercontent.com/3448386/202175752-18b80bd1-960e-49e2-bc82-1ea777153b33.png)
