### ISSUE TITLE
Reminder option? 

### ISSUE THREAD

**Issue by Beach77** [billthefarmer/diary#209]
Is there any way to have the app remind me of an event? Say I have an appointment and I want to be reminded the day before for example.

**Comment by billthefarmer** [comment]
You can create calendar events from an entry and add calendar events to an entry. See [README](https://github.com/billthefarmer/diary#events). Creating an event also creates a reminder. Use the Calendar app to edit events.

**Comment by billthefarmer** [comment]
Another way to do this is to use the app widget and make a suitable diary entry...

![Screenshot_20230207-131230 1](https://user-images.githubusercontent.com/3448386/217254728-02974502-74e1-41d3-bf13-c6866069b15b.png)
