### ISSUE TITLE
'Go to date...' feature, quicker way to jump to specific year/month?

### ISSUE THREAD

**Issue by eternalbit** [billthefarmer/diary#210]
When using the 'Go to date...' feature to access the entry for a certain date which is a few years in the past, one has to tap many times to get to the right month.

Is there a quicker way to do this?

I did not set up an index page.

**Comment by billthefarmer** [comment]
RTFRM &ndash; swipe up and down in the custom calendar, see https://github.com/billthefarmer/diary/issues/184#issuecomment-1009847738, [README](https://github.com/billthefarmer/diary#swipe-up-and-down), [help](https://github.com/billthefarmer/diary/blob/master/data/help.md#swipe-up-and-down)

**Comment by eternalbit** [comment]
Sorry :| .. I did take a glance at the manual before opening this. Should have used Ctrl+F or read it completely, which I did not.

Thank you for making this awesome app with just a few kb total size.
