### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by fwfsf** [billthefarmer/diary#211]
1. Multiple journals can be created on the same day, and the journal title can be modified
2. global search 
3. This application can not only copy images, but also copy other linked files
4. Add a to-do list to the settings. The current to-do list needs to be manually entered

The following is the recommended application file directory structure

![screenshot](https://user-images.githubusercontent.com/107751295/227517850-63cb4e9a-7e39-408f-b6ba-107809890c15.png)

**Comment by billthefarmer** [comment]
1. If you want journals, try my [Notes](https://github.com/billthefarmer/notes) app.
2. The find all menu option searches all entries.
3. The copy function is limited to images to avoid duplication of large files &ndash; see #115.
4. How do you add a to-do list to the settings?

**Comment by fwfsf** [comment]
1. Okay, I'll try it.

2. Sorry, I initially thought clicking 'Search' would automatically search for all files, but I didn't notice that the 'Find All' button was also included in the settings later on.

3. Regarding the issue of large files, I think adding an option to automatically copy all linked files would be more convenient than manually copying each time in the future, and saving all linked files in a single folder is easier to manage. For example, the `_resources` folder in the above image. If multiple markdown files introduce the same linked file, the application only needs to copy the address of the linked file under the attachment folder. The application can record the number of references of the linked file in all markdown files. If the number of references of the linked file is 0, the application can delete the linked file under the attachment folder.

4. Manually enter the to-do list.
[Manual.webm](https://user-images.githubusercontent.com/107751295/227718149-af263cc9-d680-484f-8914-7fce057b6d2c.webm)

- Click the Add to-do list button to add a to-do list, `- [ ]` will be automatically generated at the beginning, every time you click the Enter button, it will automatically add `- [ ]` , and twice press the Enter button to cancel to-do list.
[Auto.webm](https://user-images.githubusercontent.com/107751295/227718169-a1bd9d3e-7120-4ba1-badc-340aafdc82a4.webm)
	
- Currently, this application can only manually add to-do list, which can be more convenient if it can be automatically added in the settings.
