### ISSUE TITLE
option to save files for basic text compatibilty with rednotebook

### ISSUE THREAD

**Issue by nutpantz** [billthefarmer/diary#212]
rednotebook is a very popular desktop diary app  
 
there is very little different between the text files of this android app and rednotebook  
  
mostly its the path where the files are saved and named.   so filename and path as an option
 
now if markdown is used im not sure how that would work
but i am thinking basic text files only would be needed for a large number of people.   
 
mind you if there was more compatibility it would open up a lot of users for both applications.

https://rednotebook.app/help.html
https://rednotebook.app/
https://github.com/jendrikseipp/rednotebook

**Comment by billthefarmer** [comment]
There are a number of points. Rednotebook  appears to use it's own markup scheme different to markdown. The docs I looked at don't appear to mention how entries are stored. You can sync your diary folder using Syncthing or any other app that can sync a real folder, as documented in the [README](https://github.com/billthefarmer/diary#sync). You can share text from entries using android built in facilities. You can share diary entry files using a file manager.

**Comment by nutpantz** [comment]
can you share the lasts months diary entries all at once?   
i don't know about you but i can go two or three months before i copy all my diary entries to my desktop.  
at the moment i copy all the files to desktop and copy and paste each one into each day on rednotebook.
[2023-06.txt](https://github.com/billthefarmer/diary/files/11924597/2023-06.txt)   

rednotebook appears to save the entries as text files by month. with each day inside.     
  
i have found no better desktop diary app then rednotebook. im sure it has its quirks.
between rednotebook and diary i cant think of anything that a user could every need more.
rednotebook has a huge following. as i expect diary has also. it would be nice if they were more compatible.

**Comment by billthefarmer** [comment]
If you use something like Syncthing you can get an up to date copy of the Diary folder on your desktop which you can use either bidirectionally or read only. I just tested this, it works fine in both directions.

**Comment by nutpantz** [comment]
The main point of this suggestion, is that there is no easy way to read the files on the desktop, short of each day with a text reader. 
A optional save format would make it much more compatible with rednotebook even if only ascii text was compatible.  
Maybe someday rednotebook will be fully markdown supported.

**Comment by billthefarmer** [comment]
I have had several requests to make the app compatible with other applications &ndash; #138, #70, #33, #19. The app does what it does and uses the file structure it uses and it isn't going to change. It's far too complicated already.
