### ISSUE TITLE
White background in dark mode on main note view pages

### ISSUE THREAD

**Issue by wrathofthomas** [billthefarmer/diary#213]
Hi Bill!
Thanks again for this app. I use it on the daily.
For some reason despite the app being in Dark mode, it's only the editor mode that has grey bg light text. When I open the app initially or am "viewing" any notes (basically any time the bottom right button shows a pencil), the background is always white while text is black (this is very bright and white). Do you mind making it so that dark mode allows this main part of the app to also be dark background light foreground?

AMOLED white text on black would be even nicer!
Thank you.

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/diary/issues/106#issuecomment-529879697, [dark.md](https://github.com/billthefarmer/diary/blob/master/data/dark.md), linked to from the [README](https://github.com/billthefarmer/diary#readme).

**Comment by wrathofthomas** [comment]
Got it! So now I can make the "view mode" black with white text, but I've looked in the readme and sample files and now I can't figure out how to make the editor modeb have black background white text as well. Can I do this with CSS also? Thank you!
________________________________

**Comment by billthefarmer** [comment]
The 'view mode' is effectively a web page which is why you can use css and scripts. That doesn't work for the text editor, you need to code a new theme.
