### ISSUE TITLE
Hashtag Support?

### ISSUE THREAD

**Issue by EternityForest** [billthefarmer/diary#214]
It would be cool to be able to have a list of tags that you could click, to find all pages with that tag(Or, with a non empty section with that heading, for better template support), the way you can on Obsidian.

It would also be pretty cool if the calendar view could display some indication of tags.

And database indexing could be slow, or else not sync right, so you could just do folders named after the tags, that replicate the main directory structure, but with just the matching files, represented as symlinks to the main files(Or perhaps just files containing the main filename, to preserve support for filesystems that can't do symlinks).

When you finish editing, you could check if the list of tags for that page has changed, and only touch the FS if it has, to keep everything super responsive and avoid unnecessary sync history traffic.

Or, it might be enough just to use brute force search and not index at all, except for the listing of different tags, which could just be a manual list?

**Comment by billthefarmer** [comment]
There is nothing stopping you using hashtags. or front matter with the search function. Front matter is ignored by the commonmark parser/renderer so it doesn't appear in the formatted pages. This app is already too complicated, I don't intend to add further functionality unless someone comes up with something useful that is reasonable to implement.
