### ISSUE TITLE
Backup .md file not showing as i type. Showing question marks.

### ISSUE THREAD

**Issue by Oronno100** [billthefarmer/diary#216]
I really appreciate a great software you have created which is very helpful for me. I worte a lot of regular journals into the software and unfortunately few days ago I have to flash my device. Before flashing i backed up dairy. But now it is showing no content but question mark text. I contain text in Bangla Language via gobard. Please help me out. Please please. 
![Screenshot_2023-08-05-23-54-11-536_org billthefarmer diary](https://github.com/billthefarmer/diary/assets/141516764/0d41c4c5-18db-4483-a29a-79fbfbe1bbe3)

**Comment by billthefarmer** [comment]
This text is not utf-8. If you back up using the **Backup** menu option you get a zip file which can be restored to the original diary content. Whatever you did has corrupted whatever you saved.

**Comment by Oronno100** [comment]
I backed it up via swift backup app. Isn't there any way possible to restore or retract original content from all those files? I have a full folder of "dairy". My first baby will be born soon and i was writing the journals for him/her as a daily life experience and expecting of parents during pregnancy. So i guess u can understand how much important it is to me.

**Comment by Oronno100** [comment]
> This text is not utf-8. If you back up using the **Backup** menu option you get a zip file which can be restored to the original diary content. Whatever you did has corrupted whatever you saved.

I backed it up via swift backup app. Isn't there any way possible to restore or retract original content from all those files? I have a full folder of "dairy". My first baby will be born soon and i was writing the journals for him/her as a daily life experience and expecting of parents during pregnancy. So i guess u can understand how much important it is to me.

**Comment by billthefarmer** [comment]
I don't know anything about swift backup. If it restored the diary folder correctly the app would work correctly.

**Comment by Oronno100** [comment]
> I don't know anything about swift backup. If it restored the diary folder correctly the app would work correctly.
