### ISSUE TITLE
Sharing links into Diary

### ISSUE THREAD

**Issue by pudah** [billthefarmer/diary#217]
When sharing from a page in a web browser, most apps seem to get the page title and URL. For example, if I share from a webpage into K-9 mail, the page title ends up in the email subject and the URL is in the body of the mail.

When I share into Diary, the info that shows up in the text of the link created in the diary entry is the last node of the URL. If there is nothing after the last node, it ends up with null.

A few  examples...

If I am on https://www.w3schools.com and share into Diary, it results in `[null](https://www.w3schools.com/)`.

If I go to the JavaScript tutorial at https://www.w3schools.com/js/default.asp and share into Diary, the result is `[default.asp](https://www.w3schools.com/js/default.asp)`. When I share into other apps, I would get `[JavaScript Tutorial](https://www.w3schools.com/js/default.asp)`.

If I share from https://spec.commonmark.org/0.30, it results in `[0.30](https://spec.commonmark.org/0.30/)` instead of `[CommonMark Spec](https://spec.commonmark.org/0.30/)`

Would it be possible to change Diary to function like most other apps and use the <title> of the web page if there is one? I think this would make diary entries that refer to links shared from web pages much more meaningful.

**Comment by billthefarmer** [comment]
I have tested this. None of the apps that I have tested that can insert a link do anything other than insert the Uri. In order to get the page title it is necessary to fetch the web page and parse the title, which would have to be done in the background because of potential delays and errors due to the device being possibly offline. It's also outside the scope of this app.

I have added an add link dialog to allow editing of the link title.

![Screenshot_20230901-130122 1](https://github.com/billthefarmer/diary/assets/3448386/2d02764f-515b-48ef-b2c7-888c9b0429f7)

**Comment by pudah** [comment]
> None of the apps that I have tested that can insert a link do anything other than insert the Uri. In order to get the page title it is necessary to fetch the web page and parse the title

Doesn't the URI contain the page title in the subject?

When I intercept the share intent using [Intent Intercept](https://f-droid.org/en/packages/uk.co.ashtonbrsc.android.intentintercept/), I can see `android.intent.extra.SUBJECT=xxxxxxx`  where xxxxxxx is the title of the web page, in the URI data.

**Comment by billthefarmer** [comment]
It varies. Firefox sends the title as extra SUBJECT, Chrome sends it as both TITLE and SUBJECT, the other browsers I tested just send the URL as TEXT. Diary looks for the title as extra TITLE, which I thought was fairly logical at the time. However the idiosyncrasies of android apps never cease to foil the developer.

![Screenshot_20230901-164832 1](https://github.com/billthefarmer/diary/assets/3448386/6bf4d94b-c38b-4648-a607-7a8b5cf026bf)

**Comment by pudah** [comment]
> It varies. Firefox sends the title as extra SUBJECT, Chrome sends it as both TITLE and SUBJECT, the other browsers I tested just send the URL as TEXT. Diary looks for the title as extra TITLE, which I thought was fairly logical at the time. 

I mostly use [Mull](https://github.com/divested-mobile/mull-fenix) (based on Firefox), which is probably why I am used to seeing the page title in the SUBJECT extra.

Would it be difficult to adapt Diary to work with these variations on how the intents are sent? Possibly pulling the title from SUBJECT if TITLE is not present?

> However the idiosyncrasies of android apps never cease to foil the developer.

Being a developer must sometimes be an incredibly frustrating endeavor!

**Comment by billthefarmer** [comment]
Yes, I did that. That is in the next version.

**Comment by pudah** [comment]
Excellent. Thanks so much.
