### ISSUE TITLE
Jump to Template page 

### ISSUE THREAD

**Issue by Sayayaya** [billthefarmer/diary#218]
Hello,

The idea of a template page is great but unless your devices date picker happens to let you jump by years (mine does not) then it becomes a 10 minute exercise just to get to the template page.

Please consider adding a more finger friendly way to get to the Template page such as a link from the settings or something else.

**Comment by billthefarmer** [comment]
From the README/help...
> ## Swipe left and right
> Swipe left and right with two fingers in the diary page will show the
> next or previous day, or in the custom calendar will show the next or
> previous month.

> ## Swipe up and down
> Swipe up and down with two fingers in the diary page will show the
> previous or next month, or in the custom calendar will show the
> previous or next year.

In the android date picker if you tap on the year you get a scrolling year picker...

![Screenshot_20230904-082637 1](https://github.com/billthefarmer/diary/assets/3448386/9467376a-cd57-4c2e-9164-0504c775c470)
