### ISSUE TITLE
automatic selection is annoying

### ISSUE THREAD

**Issue by 1erpasch** [billthefarmer/diary#219]
Please remove the automatic selection function between the quotation marks "this is a text" and the parenthesis (this is a text).
Or add the functionality to switch it off.
When I wanna select a word in between those "" and (), the whole text gets selected. 
In the very most cases this is super annoying.
Thanks

**Comment by billthefarmer** [comment]
I have added an option to disable the extended selection

**Comment by 1erpasch** [comment]
<3<3<3
Thanks!
When will the updated version will be released?
