### ISSUE TITLE
feature request: upgrade TargetAPI

### ISSUE THREAD

**Issue by ivysrono** [billthefarmer/diary#220]
It is 28 for Android 9 now.

**Comment by billthefarmer** [comment]
The app was designed around a hierarchical folder structure in the device storage. If the target API is increased that is no longer possible. There is an API for letting the user choose a folder with a hint, which I have tested and found it ignored the hint. The alternative is to use the app's storage which get deleted if the app is uninstalled. AFAIK, there is no reason for the app to increase it, only pain.
