### ISSUE TITLE
Include misspelled words in search results

### ISSUE THREAD

**Issue by rahqbo** [billthefarmer/diary#222]
Hi,

I do not use auto correction and sometimes I write my diary entries too fast and produce misspellings. Is it possible to include words that are close to the search term in the search results? The way it is now, any misspelling will not be found, even if it's only one letter missing or swapped.

Thank you for the app

**Comment by billthefarmer** [comment]
The text search function locates the first and subsequent instances of what is entered interactively, which is what was originally requested. To find misspelled words you can try entering the part of the word that was possibly spelled correctly or another word that might be near what you are looking for.

**Comment by rahqbo** [comment]
Allright, thank your for the response.
