### ISSUE TITLE
Feature Suggestion: Retrospection

### ISSUE THREAD

**Issue by agschaid** [billthefarmer/diary#224]
Hi,

this is only a feature "suggestion" and not a request, since I am basically covered on my other system.

I sync my diary folder between my android phone and my laptop. On my laptop I have a little script that creates a "daily retrospection". That means it opens up my editor with the following diary entries (if they exist):

* 1 week ago
* 1 month ago
* 6 months ago
* 1 year ago
* 2 years ago
* 5 years ago
* 10 years ago
* one random entry

I read those old entries, pick up on old thoughts, review old ideas, re-learn stuff, get reminded of important things in my life and get a feel of what has changed and was has stayed the same . . . 

This little feature has really benefited my motivation to write a diary (since I know that those entries WILL be read some day) and the benefit I get from that (both emotional and practical).

I would like to suggest a similar feature for `diary`.

I was thinking of something along the lines of a daily notification (if that feature is enabled) and menu entry to open an overlay of left-right-swipeable diary entries.
But I guess that is A LOT of work.

Maybe it would be easier to do this with a "dynamic index" page. I am not quite sure, but I think those index pages can not perform the necessary date-arithmetic for relative dates right now. Let alone random dates.

Sorry for not fleshing out the idea more. As mentioned above I myself am already covered for 99% of my time and just wanted to place the suggestion here. But I am open for discussing details and thoughts.

**Comment by billthefarmer** [comment]
That's a bit too much like faecebook for me. I deleted my account about ten years ago.
