### ISSUE TITLE
Issue: Wrong icon size

### ISSUE THREAD

**Issue by xiaochen2002** [billthefarmer/diary#225]
As the title says, the Diary icon size is incorrect on my home screen.

I was using 1.66 version in past 2 years and when I update to the current newest 1.104, the icon became small.

It looks like this:
![IMG_20240217_123221](https://github.com/billthefarmer/diary/assets/47514706/236e2974-b1da-4f6a-ac37-dee30c787616)
![IMG_20240217_123545](https://github.com/billthefarmer/diary/assets/47514706/7d8ecb19-b1c5-465c-bc62-cd278643aaab)

I'm using Xiaomi 6 (sagit) with MIUI11.0.5 (Android P), using default miui themes.

**Comment by billthefarmer** [comment]
Some launchers don't seem to able to cope with vector icons. These are screenshots from my test devices:

Moto G running android 7.1, the buses icon is an image
![Screenshot_20240217-150046](https://github.com/billthefarmer/diary/assets/3448386/61181214-e22f-4c46-aa5d-3211d3db927b)

Pixel 3a running android 13, the notes icon is an image, the diary and print icons are vector
![Screenshot_20240217-150916_Trebuchet](https://github.com/billthefarmer/diary/assets/3448386/fc2aa242-8231-410c-bfbb-75be7a4241a7)

Samsung Galaxy Tab A running android 11, the diary icon is pixelated, dunno why
![Screenshot_20240217-150538_One UI Home](https://github.com/billthefarmer/diary/assets/3448386/cfa589d6-23e8-45a6-a97a-e50750ab0977)

**Comment by xiaochen2002** [comment]
Oh it looks just like what you said..I verified this  using Microsoft launcher and found that Diary does displayed correctly there.
Since it's not a critical bug, Ill close this issue and ignore that. Thanks for the reply, and thank you bring us such a wonderful tool : )
