### ISSUE TITLE
Suggestion: change the page turning operation method 

### ISSUE THREAD

**Issue by xiaochen2002** [billthefarmer/diary#226]
The current version of the page-turning method is double-finger swipe left and right. However this method of operation is very susceptible to misidentification. Diary often switch to previous/next month, as it thinks I'm swiping up and down using two fingers while I wanna go to previous/next day.
In older version (I know one is 1.66) the turning page method is one finger left and right, which is much convenience and barely make mistake. 
I think that the Diary user mostly installed on their phone or some device easily to carry with. this means one hand gestures use much more than two fingers gesture. On the premise of this assumption, you'll find two fingers swipe turn page is much harder, than the previous Diary version.
So I suggest change this back, like the old version do.
Can't appreciate more if you'd take my advice.

**Comment by billthefarmer** [comment]
Swipe gestures for changing the date were made two finger to avoid conflict with scrolling and editing. See #183.

**Comment by xiaochen2002** [comment]
I see what said in #183. but imo that's not a good solution:
First is what I said upper
Second is, while editing, switch entity gesture should be disabled cuz user are typing, no intend to switch to previous/next day (maybe sometimes do wanna add some words on yesterday when writing today, but what I always did is finish editing then go to that day)
Third, you mentioned that scrolling also cause misidentification, yep this conflict does exist, but it has a low chance of triggering. And when it happens to me, I only think that was my mistake, not Diary's(I drew too slanted)

Hope these could help prove my suggestion.
