### ISSUE TITLE
Image and video size problems >_<

### ISSUE THREAD

**Issue by LonerPlayzGamez** [billthefarmer/diary#227]
As a diarist myself, I really love this app. It helps me journal everyday and capture my thoughts instantly. I also love the simplicity and the capability to add any medias(image, video, audio, etc.) 

However, several weeks ago or a few months ago, I found this problem. I was playing around a bit in the script place and I am sure I did not insert anything. I am a less tech person since I am just a beginner towards coding then when I saw the entries. The appearance of the images/videos are too big. I tried to clear the script but I know that I don't put anything in there and fix everything in the settings but the appearance is still the same. I also tried to delete the app and install again but it's the same. This bug caused me to lose my interest in journaling + I have to switch back to my paper diary :(

Here are the samples of the problem and I hope there is a way to fix it.
![received_645039774355919](https://github.com/billthefarmer/diary/assets/162767676/972d9cb0-11ba-41cc-9843-c59db660b87e)
![received_843982517483838](https://github.com/billthefarmer/diary/assets/162767676/b7013733-6618-4320-858d-c9eb3ce154cf)

**Comment by billthefarmer** [comment]
See the [README](https://github.com/billthefarmer/diary#styles) on styles and scripts. If you don't want any styles or scripts, delete anything in `Diary/css` and `Diary/js`. Or remove the folders. Or change the `styles .css` file to `@import "file:///android_asset/styles.css";`.

**Comment by LonerPlayzGamez** [comment]
Just deleted the css and js files. Then I went to check the appearance of the images/videos and they are now normal! Thanks to your help. I love your app and keep up the good work <3
