### ISSUE TITLE
Suggestion: Add name of the day in page heading

### ISSUE THREAD

**Issue by cboneth** [billthefarmer/diary#228]
At the top of every page there is a heading with the exact date but it doesnt say the name of the day. Please add this small feature for better context. Thanks.

**Comment by billthefarmer** [comment]
The day of week is shown in landscape and on larger devices.

**Comment by cboneth** [comment]
Why not make a shortened variant visible i portrait mode? It would be useful in case when using a phone which is most commonly held vertically..

**Comment by billthefarmer** [comment]
See #166. It is annoying when people keep raising the same thing over and over because they can't be bothered to check old issues.

**Comment by cboneth** [comment]
It's ok. Thanks for the clarification.
