### ISSUE TITLE
If no text is in an entry before an HR, the rendered view is empty

### ISSUE THREAD

**Issue by rpavlik** [billthefarmer/diary#229]
Put this into a new entry:

```

---

This is a test.
```

and hit the FAB check button.

The "view" screen will remain solid white as if there was no entry, though if you click the FAB pencil the text content is still there. (Scary thing to have happen!)

However, if at least some text precedes the three dash HR, then it all displays fine.

```
asdf

---

This is a test.
```

**Comment by billthefarmer** [comment]
See #167, [README](https://github.com/billthefarmer/diary#markdown).

**Comment by rpavlik** [comment]
oh right yaml front matter.  Didn't expect that parsing interpretation since I only had a single line, not two lines of `---`.

**Comment by billthefarmer** [comment]
Looking at the code for the [commonmark-java](https://github.com/commonmark/commonmark-java) [YAML front matter](https://github.com/commonmark/commonmark-java#yaml-front-matter) it just looks for the starting pattern `---` and then parses YAML until it finds the ending pattern. So any other pattern for a horizontal rule would defeat it.
