### ISSUE TITLE
Own entry/entries gone after app update

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#24]
I'm using _Diary_ only irregularly for retaining funny experiences that are caused by our little daughter.
I had only one entry up to now and wanted to add a second one this morning.... - but it seems that my first entry was deleted! :-(
When opening _Diary_ , it looks like a fresh, new installation: The "description entry" (with the description how to use) is at the current date, the formerly entered event/date was gone!

I'm updating _Diary_ via the F-Droid app store.
I guess that the app update updated the diary's entries as well, due to a new "description entry", and killed my own, existing entry as well...

**Comment by billthefarmer** [comment]
To delete an entry the user must remove all the text on a page and go to another page or quit the app. The app contains no functionality for removing entries. Did you change the diary folder? Uninstalling the app also does not remove entries, as they are in public storage. The help text only gets copied to the current entry if there are no entries in the diary, so as to be useful for new users.
