### ISSUE TITLE
Feature request: New option "Hide ' empty' dates dates(i.e. dates without entries)

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#25]
I'm only rarely using _Diary_ , so it's not an "every day app"; only funny events caused by our little daughter are entered.
For this reason, it would be great to have an option to see only "used" dates / diary entries (or hide the "empty" dates).
By having such an option, it would be easily possible to browse all remembrances, even if they are not in daily sequence.

**Comment by billthefarmer** [comment]
If you use the custom calendar, dates with entries are highlighted. The next and previous buttons go to the next and previous entries, skipping all the dates between.
