### ISSUE TITLE
Regression on version 1.18

### ISSUE THREAD

**Issue by marcoM32** [billthefarmer/diary#29]
On the last version 1.18 the swipe (up/down) action causing impossibility to scroll down the page because the motion is too sensible. How we can do to fix this problem?

**Comment by billthefarmer** [comment]
I increased the swipe margin so you get a swipe up or down with a big swipe, and a scroll with a small one.

**Comment by billthefarmer** [comment]
The other thing I forgot to mention, if you zoom in slightly, with a two finger gesture, that turns the swipe off completely so you can swipe up, down, left and right and it stays on the same entry.

**Comment by marcoM32** [comment]
it's true, thenks! but it is not a final silution...

**Comment by swalladge** [comment]
Can this swipe action have a setting to disable it  or removed altogether? It's unbelievably annoying and unintuitive.

**Comment by billthefarmer** [comment]
Ok, I have commented that out for the moment until someone thinks of a better way of doing it.

**Comment by marcoM32** [comment]
Why not use a swipe with two fingers to keep the action? surely this implementation not should disturb during usage... or you might think of a prolonged click action on the "Previous day" button or on the "Next day" button...
It could be an idea possible?

**Comment by billthefarmer** [comment]
Yes, that works. I have included it in the next version.
