### ISSUE TITLE
Version 1.02 on F-Droid requires phone permission

### ISSUE THREAD

**Issue by jaller94** [billthefarmer/diary#3]
Hi,

the new version 1.02 which has been released on F-Droid yesterday, requires the permission to read the phone status and identity. This is a change which is not here in the repository nor mentioned in the changelog.

Diary (Personal diary or journal) - https://f-droid.org/app/org.billthefarmer.diary

Could it be that something fishy is going on with that version or am I missing something?

Greetings
Jaller

**Comment by billthefarmer** [comment]
I noticed that after I had posted it. It's not in my sources, it may be in the library I used for the custom calendar. I will check next week when I get back to my development machine.

**Comment by billthefarmer** [comment]
It doesn't appear to be in the custom calendar. I shall have to check further.

**Comment by billthefarmer** [comment]
I eventually found it in the docs - https://developer.android.com/studio/build/manifest-merge.html#implicit_system_permissions. The custom calendar library has no targetSdkVersion set, so WRITE_EXTERNAL_STORAGE and READ_PHONE_STATE get added automatically.
