### ISSUE TITLE
Trouble with localized folder name

### ISSUE THREAD

**Issue by cpfeiffer** [billthefarmer/diary#31]
In earlier versions, the folder containing the .txt files were named "Diary", but now it is named "Tagebuch" (in German). This causes all previous entries to not be accessible anymore (and a short heart attack ;-)

Copying the files over fixes this, but maybe localizing the folder name is a little fragile.

**Comment by billthefarmer** [comment]
I don't understand that. The original name of the diary folder is embedded in the code, not part of the translation. Some of the people who have contributed translations have changed the name of the app, not all, but that doesn't affect the folder. There is an option to change the folder in the settings so you could have changed it back, however it got changed in the first place.

**Comment by cpfeiffer** [comment]
I think the problem is that we previously had the hardcoded `Diary` name and later that was made configurable. The preferences get the localized version as default in `preferences.xml`:
```android:defaultValue="@string/appName"```

**Comment by billthefarmer** [comment]
Yes, that was an unintended side effect of adding a German translation. I shall have to change that to a hard coded name, which shouldn't affect existing users because the preference is already set.

**Comment by cpfeiffer** [comment]
Thanks :-) :+1:
