### ISSUE TITLE
Loosing data

### ISSUE THREAD

**Issue by kai11** [billthefarmer/diary#32]
Recently I lost a lot of typed text from today diary entry.
I edited, then shared few links then edited again.
After hour or two I tried to update text and it had only few lines from before I shared links.
I was in markdown mode.

**Comment by billthefarmer** [comment]
The app automatically saves pages every time something happens, like the user changing pages, opening another app or whatever. The only way I have found to make it lose data is by installing a new version using the debugging facility while the app is running.
