### ISSUE TITLE
[Feature Request] Allow custom patterns for file paths

### ISSUE THREAD

**Issue by zoharsnir** [billthefarmer/diary#33]
Allowing full filename path to be customized with date tokens would allow users make this App a companion to other Diary systems they use (as long as it's clear text/markdown). This is a must for users that want to maintain their diary from both PC and Mobile.

Users of vimwiki, for example, will change the path from the current default of:
`Diary/%Y/%m/%d.txt`
to something like:
`vimwiki/diary/%Y-%m-%d.wiki`
Users of other systems can choose another pattern that works for them.

**Comment by billthefarmer** [comment]
I forked this app from a very basic but well written diary app. All the infrastructure for organising diary pages by month and year in hierarchical folders was already in place. There is no template for the folder structure, it is embedded in the code. To change that would mean starting again from scratch, which I am not going to do.

**Comment by paupin2** [comment]
@billthefarmer are you willing to consider a PR implementing this?

**Comment by billthefarmer** [comment]
As I have said above, it would require a major rewrite, which would probably cause all sorts of other problems, including possible performance issues - see #70, #75.
