### ISSUE TITLE
Encrypt diary option

### ISSUE THREAD

**Issue by d1d4c** [billthefarmer/diary#39]
Add a Encrypt diary option.

Thanks!

**Comment by jeisoncp** [comment]
Encryption would be a grate feature!

**Comment by billthefarmer** [comment]
That's what you've got the Encryption feature in settings for. That way you secure everything, not just the diary. I'm not a believer in duplicating functionality already available.

**Comment by iggapres** [comment]
Sorry to comment on a closed isue, but ... I'm interested in such a feature too and I don't see it as a duplicate of system wide encryption.

My point is that I can lend my phone to friends/relatives, but I don't want them to read my diary.

Same as my house: all family member has the key (system wide encryption), but I alone know the password of my computer, even if it's inside my house (local encryption).

Thanks for reading and considering reopening this issue.

**Comment by billthefarmer** [comment]
A better way to deal with that particular issue is to use user accounts, you can also add a guest account. According to the docs, each user gets their own data and apps. You can also set up restricted profiles. I wouldn't lend my phone, but that's a personal issue.
