### ISSUE TITLE
Bug: safe button covers text, when input is RTL

### ISSUE THREAD

**Issue by igalic** [billthefarmer/diary#41]
I've been using diary to record my progress of learning Persian.
Adding new words to their appropriate dates makes it painfully obvious how slow that is going ;)

now, copy / paste works fine here, however, when I'm practicing a word myself, it gets tricky, because the input text is usually covered my the safe button

![screenshot_2018-03-04-12-35-40-084](https://user-images.githubusercontent.com/497249/36945061-aa667004-1fa8-11e8-86da-b4a2686af9da.jpeg)

**Comment by billthefarmer** [comment]
You can temporarily get rid of it with a long touch. A long touch on the background will bring it back. Also it is translucent so you can see the text behind it. It is a fundamental part of the Material design API, so for a paste button to be there is IMHO, a mistake. That's not part of the app, I assume it's part of the Persian input method. If you look at the closed issues, you can see that others have raised this issue.

**Comment by billthefarmer** [comment]
I misinterpreted what you said, I thought the text under the done button was part of the input method. So ignore the part about the paste button.

When you first run the app, with no diary entries, the help file gets copied to the current entry. You can move it to another date or delete it, but it does explain the user interface.

> ## Editing
> In markdown mode the **Edit** button floating above the page allows
> editing entries. The **Accept** button restores the formatted view. A
> long touch on the button hides it until the device is rotated or a
> long touch on the page.

**Comment by igalic** [comment]
thank you very much for all your clarifications!
