### ISSUE TITLE
feature request: nextcloud sync

### ISSUE THREAD

**Issue by cast-away** [billthefarmer/diary#42]
thanks for such a great app, would it be possible to add an option to sync to a remote storage such as nextcloud?

**Comment by billthefarmer** [comment]
It already does, just add the diary folder to the synced folders or move the diary folder to a synced folder. The same applies to any flavour of cloud storage.

**Comment by cast-away** [comment]
Syncing folders on android is not fully supported in Nextcloud. I don't know about other services but I assume there are similar limitations, which is why some apps like [Joplin](https://github.com/laurent22/joplin) (also on github) offer integrated sync. I was hoping to have the same functionality in Diary.

**Comment by billthefarmer** [comment]
You're quite right, it doesn't. It provides a very slick interface that won't do the obvious thing - sync a folder on the device. Now I've got an account I don't want and can't delete just to test it.

The problem with supporting one particular cloud storage interface is that that's just one out of many. And they probably all have their own android support library.

**Comment by cast-away** [comment]
Yup, I was pretty surprised myself that was not a standard feature.

I understand implementing this might be tricky. Maybe this part of Joplin's code could be used? I am not a programmer myself (happy to test though) but there seem to be some elements in common between both projects, such as storing the information in markdown files.

**Comment by billthefarmer** [comment]
I checked two more cloud storage services, Dropbox and Google Drive. Neither of them either offer a synced folder in the file system or will sync a folder.

I don't know about Google Drive, but Dropbox has a Dropbox folder in among the personal folders on my desktop and anything put in it including folders, is synced providing the service is running. There is no reason that I can see why they can't offer a similar mechanism on Android.

**Comment by gilcot** [comment]
In another way, apps shouldn't have to add extra lines of code to be synchronized by a service; there should be an Android unique interface. And when it comes to folders, the service provider's app should perform that stuff by itself: sync a list of directories path it can read; apps shouldn't have to support every different providers by their own...
