### ISSUE TITLE
Links inside diary are not supported

### ISSUE THREAD

**Issue by Self-Perfection** [billthefarmer/diary#43]
Let's say I have text in diary entry:
`... in continuation of [Sunday](./11.txt) events ...`
The word "Sunday" becomes highlighted as link, but tap on this link does not lead to expected result. Linked file is displayed, but:
* It is not processed as markdown, i.e. is shown as plain text
* It seems it is shown in ASCII encoding, but UTF-8 is expected as for rest of entries
* Date label in top bar is not updated
* "Back" button does not return to the date that leaded to current file

**Comment by billthefarmer** [comment]
There is a simple reason for this - it was not envisaged that markdown links would be used to reference other diary entries, but used to open external web pages. I am working on an enhancement that will address some of your points. It will be in the next version.

**Comment by Self-Perfection** [comment]
Just got version 1.26 from F-Droid and it handles links to other diary entries in expected way. Thank you!
