### ISSUE TITLE
uploaded image becomes unreadable after the app restarts

### ISSUE THREAD

**Issue by fabianmani** [billthefarmer/diary#44]
#### Expected behavior
I expected my added media images will be accessible even after closing and restarting the app.

#### Actual behavior
The added media becomes unreadable after app restart 

#### How to reproduce
* Download and open the app. 
* click on menu, then click on add media.
* choose an image and upload.
* close the app and open it again 

* Device: Tecno K7
* Operating system: Android 7.0
* App Version: 1.25

#### Recording Of The Bug
https://youtu.be/oSSAMz7jzWQ

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/uploaded-image-becomes-unreadable-after-the-app-restarts">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by billthefarmer** [comment]
I can't reproduce that. You didn't make it clear, but I am assuming from the file name that you had copy images turned on in settings. I've tried it on two devices running 7.1.2. Is the image file in the diary folder? You can check with a file manager, or even the file picker you get when you select add media in the diary app.
