### ISSUE TITLE
WebView scroll position lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [billthefarmer/diary#47]
Scroll WebView and then rotation screen. Scroll position should persist, however, it gets lost after device rotation. It's annoying because user has to manually scroll it to the expected position.

![screen shot 2018-04-13 at 1 11 20 pm](https://user-images.githubusercontent.com/38213896/38717923-6d13d0aa-3f1c-11e8-90cb-f4427e63bbaf.png)
Screenshot before rotation

![screen shot 2018-04-13 at 1 11 28 pm](https://user-images.githubusercontent.com/38213896/38717927-7192a336-3f1c-11e8-9b48-3648f02f5494.png)
Screenshot after rotation

**Comment by billthefarmer** [comment]
Fixed in latest version
