### ISSUE TITLE
Feature: Index Page

### ISSUE THREAD

**Issue by decke** [billthefarmer/diary#48]
Diary is exactly that - a diary - but I think it would also be a great journal. The one feature that I miss for that is a custom Index page from which you can start. Nothing fancy just a setting to either start at todays date or a special page.

**Comment by billthefarmer** [comment]
I'm not exactly sure what you mean. Do you mean an item in Settings to designate a particular page as an index page, and the Diary app would always start on that page if defined?

**Comment by billthefarmer** [comment]
Ok, I have added this. I have tried to make it generic, so there are two new settings
 * Use index - use an index page
 * Index page - set a date for the index page. This defaults to 1/1/2000 and the index date picker will initially start on that date.

If `useIndex` is set the app will start on the index page unless it is receiving sent media in which case it will behave as before.

**Comment by decke** [comment]
Thanks a lot!
