### ISSUE TITLE
Change the extention of entires from .txt to .md

### ISSUE THREAD

**Issue by cbondurant** [billthefarmer/diary#49]
Diary explicitly makes markdown files. Having the files saved as .txt files is slightly disingenuous, and can cause complications if the user wishes to do any automated post-processing to the entries, while still allowing direct editing.

As an example: I am interested in hacking together a kind of journal-to-website workflow, most likely using jekyll, which requires the extension to match the formatting of the file for processing. If I wanted to be able to update entries on the fly, I would need to create a complicated script that checked for a difference between the .txt that diary created, and the .md copy, and update any time that a change is made. 

I understand that this was intended as a personal use tool, as per the name, but I feel that this is one of the kind of clean and small tools that allow for fun, hacky tool systems built on top of them, and this change would facilitate that significantly.

**Comment by billthefarmer** [comment]
If the app had been designed from the outset to use markdown, I would agree. However it was built on the previous work which used text files and I added markdown after a suggestion like yours. I have no idea how many users there are our there as GitHub and F-Droid don't provide download stats, but either the app or users would have to rename all historical entries and the older versions of the app would assume the user had no entries.
