### ISSUE TITLE
WebView state lost after exiting app and re-entering

### ISSUE THREAD

**Issue by calbee633810** [billthefarmer/diary#52]
Open Diary
Click OpenStreetMap in the WebView to open map.

Pressing home button and re-entering app or turning screen off and on will make WebView rollback to home page. But its state should persist.

Before turning screen off
![screen shot 2018-04-23 at 1 19 48 am](https://user-images.githubusercontent.com/38213896/39097823-70dd12f8-4694-11e8-8602-31b7f967908b.png)

![bug2-after](https://user-images.githubusercontent.com/38213896/39097804-36666340-4694-11e8-94f7-6638441da157.png)
After turning screen on

**Comment by billthefarmer** [comment]
Fixed in the latest version

**Comment by billthefarmer** [comment]
Retaining state between invocations is not supported.
