### ISSUE TITLE
I got an empty data file from a shared location of a .ics file and .ics files crashes my diary app from file manager 

### ISSUE THREAD

**Issue by onos1** [billthefarmer/diary#53]
Here are some videos to illustrate. 

For empty data:
https://youtu.be/fkaWj3cAVyc

And for the crash:
https://youtu.be/3i4MYL5FwAk

**Comment by billthefarmer** [comment]
This is more of the same as #51 which you haven't responded to. In the first case the app editor attempted to open the file but was unable to resolve the `content:` Uri, so you got an empty buffer with a numeric name. In the second case I don't have a clue without more information. I would be interested to know what you were expecting. I did install Telegram in response to an earlier issue but was unable to get it do do anything useful without getting someone to send me a message.

**Comment by onos1** [comment]
I think the diary app doesn't support ics files, because it opens with
calender apps, I was expecting to get details of time, location and date
from the ics file
