### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [billthefarmer/diary#55]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by billthefarmer** [comment]
Thank you, that's a good idea. You could either add to the [help page](https://github.com/billthefarmer/diary/blob/master/data/help.md) that gets copied to the current page when the app is first run, or write a separate FAQ which I would put online and link to from the help page. You can pick up some ideas from the [issues](https://github.com/billthefarmer/diary/issues) page, including the closed ones.

**Comment by olayhemy** [comment]
Awesome, I would like to write a separate FAQ with a PR and you merge it to the help page.
