### ISSUE TITLE
diary saves file names as arabic-indic numbers.

### ISSUE THREAD

**Issue by ali-hardan** [billthefarmer/diary#58]
When my phone locale is set to persian or Arabic, diary saves file and folder as arabic-indic numbers.

To see this bug:
1. Change your phone locale to Persian (فارسی).
2. Open diary app, go to settings, and back to main.
3. Pick a new date and write something.
4. Go to file manager and see where are files saved!

**Comment by ali-hardan** [comment]
It can solves the problem:

https://stackoverflow.com/questions/5316131/convert-string-to-another-locale-in-java

**Comment by billthefarmer** [comment]
It's easier to get it [right](https://github.com/billthefarmer/diary/commit/f0b46882fb94a17e1876932ecf18b548b2dbd611) in the first instance. The fix will be in the next version.

**Comment by ali-hardan** [comment]
Thanks, it now fixed.
