### ISSUE TITLE
Cycle through today

### ISSUE THREAD

**Issue by spaceChRiS** [billthefarmer/diary#6]
Hi and thanks for improving this app so much already. I thought about one little improvement: When I go back to the last day that has an entry with the arrow buttons, I cannot cycle back to today with the arrow keys. This is not a problem on a large display where the today button is visible, but on smaller displays, it would be convenient if I could go to today with the arrow buttons as well, since the today button is hidden in the menu.

**Comment by billthefarmer** [comment]
That's a function of the size of your device and orientation. It's possible to force it, but that causes other problems. I could change the order of the buttons, but that would make it inconsistent with earlier versions, and you would lose the next button.

**Comment by spaceChRiS** [comment]
You are right with all you wrote, I thought of a different solution: At the moment, if I press "left" one time from today, the last entry is loaded and the "right" button has no function. I just think of the "right" button going to today if you are on the last entry. That way, you could press "left" and check what you wrote yesterday and go back to today with the "right" button. Nothing else.

**Comment by billthefarmer** [comment]
That's dependent on how you use the app. If you use it purely as a historical diary, making entries on the day, that could work, but if you make future entries, it wouldn't. My spouse uses her real diary for everything, it's got past, present and future in it. You only have to put one character in today and go back, then the next button will return to today. If you don't want to make an entry, you can delete the character, and when you do something else, the file for today will get deleted. I will look at the logic and see if the next button can be fudged to go to today if it would be the next entry.

**Comment by billthefarmer** [comment]
I have made the previous and next buttons always cycle through today, even if there is no entry. That will be in the next version, which will also include the option of using markdown formatting for entries.

**Comment by spaceChRiS** [comment]
That's great news! Thank you very much :-D
