### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [billthefarmer/diary#61]
Hello, @billthefarmerI want to contribute in "diary" so i  want to designed a new logo for "diary" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by ggcarlosr** [comment]
Hello friend, I am also available to join by presenting a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by billthefarmer** [comment]
See #62
