### ISSUE TITLE
Feature: Add JS injection option.

### ISSUE THREAD

**Issue by ali-hardan** [billthefarmer/diary#64]
Since diary viewer supports JavaScript, it's good idea to adding JS injection option.

I want to run some actions on my text by JavaScript on all my diary pages.

**Comment by billthefarmer** [comment]
OK, that is possible. I propose that if there is a file `Diary/js/entry.js` it gets loaded by all pages, in the same way as styles. I will investigate. Let me know if you meant something different.

**Comment by ali-hardan** [comment]
Yes, this is what I mean.

Instead making `Diary/js/entry.js` and load it in all pages, you can make a `header.html` file and allow users to write any header, like writing `<script>` or `<style>` tag.

Of course, there is not much difference. Do what you think is better.

Thanks.

**Comment by billthefarmer** [comment]
I investigated including a HTML file. There is a [link type](https://www.w3.org/TR/html-imports) for this, but it is apparently not [widely supported](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports). There are [several ways](https://stackoverflow.com/questions/950087/how-do-i-include-a-javascript-file-in-another-javascript-file#950146) of importing JavaScript into JavaScript.

I have implemented this by adding a `<script></script>` tag at the beginning of the HTML in the same way as styles. There is also a menu option to edit the file.  The file is `Diary/js/script.js`, which will be used if present. Script errors get logged by the WebView in the device log file.

This will be in the next release.
