### ISSUE TITLE
Make the Edit/Save button non-FAB

### ISSUE THREAD

**Issue by kamilst96** [billthefarmer/diary#67]
It would be much better if this button simply lived on the topbar, as all other buttons. It wouldn't stand in the way, and I wouldn't have to use this button-press-to-hide-or-show workaround.

If this feature is popular, maybe add an option to choose FAB or non-FAB?

**Comment by billthefarmer** [comment]
This has come up before - #18. The button is translucent and will hide on a long touch. One of the reasons for this button is that you can only have three buttons in the toolbar unless you override the defaults. That then truncates the title on a phone. Having the page navigation on the toolbar and switching back and forth  between editing and viewing on a separate button keeps the app consistent with the android style guide and tidy.

**Comment by kamilst96** [comment]
What about if it disappears when scrolling down once, but reappears when scrolling up once? I've seen this behavior in some apps, and it was fine.
