### ISSUE TITLE
feature request: use file open dialog to pick storage location instead of text field

### ISSUE THREAD

**Issue by prg318** [billthefarmer/diary#68]
It would be convenient if the settings UI used a file browser instead of a text field for selecting where the diary files should be stored

**Comment by billthefarmer** [comment]
That's a nice idea. Unfortunately the file pickers provided by android and installed file pickers in file managers won't let you select a folder, only a file. Even when you use the official android mime type for a folder - `vnd.android.document/directory`. Selecting a folder just opens it.

**Comment by prg318** [comment]
Oh wow - I never realized that about Android :X Well I understand why you would want to keep your current solution then.  I'm going through other apps that have a similar feature (Markor, camera applications) and see that they are implementing their own UI for this.  Seems like quite an omission from Android SDK.

Cheers!
