### ISSUE TITLE
Support a flat file structure instead of dated folder hierarchy / Vimwiki support

### ISSUE THREAD

**Issue by dgrabla** [billthefarmer/diary#70]
This is a terrific app to read and edit vimwiki journal entries on the go. Vimwiki has an superb diary function to read and edit entries on the computer. It would be an awesome combo. The only problem is that vimwiki diary creates files on a folder like somewhere/[year]-[month]-[day].[configurableextension] and this android app saves the files in a folder hierarchy [year]/[month]/[day].txt  

There is an option to define where is the root of the diary. 
Do we have a feature on the pipeline to configure the name/the structure where to store the daily entries?

**Comment by billthefarmer** [comment]
I've been asked this before, see #33. As I said there it would require a rewrite of the app as the file structure is embedded in the code. Also having all your entries in one folder, IMHO, would rapidly become unwieldy and probably inefficient.

**Comment by dgrabla** [comment]
I understand, in that case maybe it is easier to add the folder hierarchy feature in vimwiki @zoharsnir
