### ISSUE TITLE
Potential UI bug: Save button in the way of cursor

### ISSUE THREAD

**Issue by iamtew** [billthefarmer/diary#71]
Lovely app, I really like its simplicity, and I don't see myself stop using it anytime soon!

There is a potential UI bug with regards to the save button. Whenever the text fills the whole page, the round "save check-mark button" covers the text and cursor and makes it difficult to work with the text there. 

Suggestion would be to perhaps put the save button on top of the page instead of the bottom, or make it fade out? I don't know what works best. My current work-around is to insert several line breaks to make have extra room in the bottom of the page. This works but would nice to have a real solution :-)

I have attached a screenshot, you can see the cursor behind the save button, in the word "maps", looks more like "m|aps".

![2018-09-26 07 27 06](https://user-images.githubusercontent.com/1183594/46059262-c3270100-c15e-11e8-9fa6-717afec57be2.jpg)

**Comment by billthefarmer** [comment]
See #67 and #18. As I said there a long touch will hide it and it is semi-transparent. And it's consistent with the android style guide. If you look at your screen dump you can read the text through it.

**Comment by iamtew** [comment]
My apologies, I should have gone through previous issues regarding this!

Thank you for the quick response and answer. 

Closing issue.
