### ISSUE TITLE
Add A Privacy Policy Statement.

### ISSUE THREAD

**Issue by HarryHeights** [billthefarmer/diary#73]
Hello there, I'm Harry. I'm a content creator. I enjoy using your software. It's been really helpful. I'd like to contribute to your software by creating a privacy policy document which would contain details of how you deal users information that's if you collect them. But if you don't it's still fine anyway to let end-users know too.

I'd love to hear your thoughts.

**Comment by billthefarmer** [comment]
I don't think it's necessary as the app doesn't make use of any users information.

**Comment by HarryHeights** [comment]
Oh okay.
