### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by princekelly1** [billthefarmer/diary#74]
Hello, I'm Kelly. I think having a privacy policy statement will be a good thing for your project seeing it kind of have functionalities that may lead to data collection on your end or not. It's a good end users are made aware of the safety of their privacy. I could draft a privacy policy statement if you wish. It's my way of contributing to open source projects.

**Comment by billthefarmer** [comment]
The app doesn't do anything except store diary pages on the user's device. I don't think it needs a privacy policy. It asks for internet access so user's diary pages can access external content and follow links, and calendar access so users can add events to the their calendar.

**Comment by princekelly1** [comment]
Ok
