### ISSUE TITLE
setting / configuration file to use .md instead of .txt

### ISSUE THREAD

**Issue by apfelchips** [billthefarmer/diary#76]
in  https://github.com/billthefarmer/diary/issues/49 you expressed your concerns about changing the default, but could you please add the option to change the file extension, so my other text editors know how to highlight my diary.
I'd suggest putting a `.diary.conf` file, be it YAML/JSON/ini in the root of the diary folder to store this setting and maybe some more.

Like I'd really love to have a flat file structure with ISO8601 (YYYY-MM-DD) filenames, the media files would be stored inside a `<date>_assets` folder when there are any to save.

Then I could add [YAML Frontmatter](https://jekyllrb.com/docs/front-matter/) with metadata about the day and process it using  a static site generator like jekyll or PicoCMS.

for example:
```
---
Mood: good
Weight: 80kg
Exercised: yes
---
```

**Comment by billthefarmer** [comment]
Android has a built in [Settings](https://developer.android.com/guide/topics/ui/settings/) API, which although it is slightly limited in the types of data that can be stored is perfectly adequate for most apps. So there is no need for the use of config files or YAML. I have been asked about flat file structures before, see #70, #33.
