### ISSUE TITLE
Custom calendar next and previous months buttons are initialed relative to today instead of selected date

### ISSUE THREAD

**Issue by Self-Perfection** [billthefarmer/diary#77]
Steps to reproduce:

1. Go to diary record for 2018-07-15
2. Run custom calendar. It shows July. That is expected.
3. Tap left arrow. Instead of June custom calendar will switch to November.
4. Afterwards next and previous buttons work as expected.

**Comment by billthefarmer** [comment]
That is fixed in the next version

**Comment by Self-Perfection** [comment]
Indeed, I can't reproduce with version 1.34. Thank you!
