### ISSUE TITLE
Possible to access future days by swiping

### ISSUE THREAD

**Issue by TesseractCat** [billthefarmer/diary#79]
The arrows at the top of the page will grey out when you reach the current day, preventing you from editing entries in the future, however if you swipe between entries you can go to a day in the future. I don't know if this is intended behavior, but if it is it would be nice to have an option to disable it.

**Comment by billthefarmer** [comment]
You can go to any date you like using the calendar. The object of this app is to duplicate the functionality of a paper diary. You can use that for anything, keeping a record of past events, future things to do, whatever. The swiping behaviour was requested and is intended.
