### ISSUE TITLE
Support left and right gesture for previous and next entries

### ISSUE THREAD

**Issue by scito** [billthefarmer/diary#8]
Support left and right gesture for previous and next diary entries.

Additionally, left and wish gesture should also be supported in custom calendar.

**Comment by spaceChRiS** [comment]
Interesting idea. Another option would be if the swipe gestures would not go through the entries but one day forth/back, independent of the day having an entry or not. This way, it would be easily possible to go to, e.g., “tomorrow” to add an entry. And it would not double the functionality of the arrow buttons.

**Comment by billthefarmer** [comment]
I haven't looked at this yet. A potential problem is that the text view and markdown view already use gestures for scrolling.

**Comment by spaceChRiS** [comment]
Did not think on that. The gestures for the text/md view are IMO more important than going to the next day.

**Comment by billthefarmer** [comment]
I have added left and right swipe gestures to the diary which go to the next and previous day. And to the custom calendar which go to the next and previous month.

**Comment by scito** [comment]
Wow, thanks. That was fast!

**Comment by spaceChRiS** [comment]
How did you solve the double meaning of the gestures in combination with the web view? I know I could wait for the new release to appear on f-droid, but I am so curious ...

**Comment by billthefarmer** [comment]
There is a function [dispatchTouchEvent()](https://developer.android.com/reference/android/app/Activity.html#dispatchTouchEvent(android.view.MotionEvent)), which allows processing a touch event and then passing it on. [Here](https://github.com/billthefarmer/diary/blob/master/src/main/java/org/billthefarmer/diary/Diary.java#L271).
