### ISSUE TITLE
Changelog pop-up

### ISSUE THREAD

**Issue by marcoM32** [billthefarmer/diary#81]
It is possible add a changelog pop-up to see the news of the last release?

![screenshot_20190104-131331](https://user-images.githubusercontent.com/16719549/50688601-7177f780-1026-11e9-9cc9-76463bc450c5.jpg)
(The image is relative to GnuCash for Android)

In this case the pop up appear after a user action on app version item in the setting menu.

Thank you

**Comment by billthefarmer** [comment]
There is a link to the [Changelog](https://github.com/billthefarmer/diary/releases) on the F-Droid app page. I could make the version text in the About dialog link to the same place.

**Comment by marcoM32** [comment]
This is a good news because the changelog description is accessible by the following json on GitHub API:

https://api.github.com/repos/billthefarmer/diary/releases/latest

it is possible fetch this in the app?

**Comment by billthefarmer** [comment]
That's very nice, but the app doesn't use JSON, or fetch anything from the web except for the markdown view when used as a browser or fetching images etc, and the API doesn't fetch the release text. Also the latest release page on GitHub is the same as the releases page less the other releases.

In fact if you link to https://github.com/billthefarmer/diary/releases/latest it currently gets redirected to https://github.com/billthefarmer/diary/releases/tag/v1.36. Whether that's a supported feature I have to idea.

**Comment by marcoM32** [comment]
Would not it be possible using a such strategy:

<code>
WebView webView = new WebView(context); 
webView.loadUrl("https://github.com/billthefarmer/diary/releases/latest");
AlertDialog.Builder builder = new AlertDialog.Builder(context); 
builder.setView(webView);
</code>

with a read only page, thet not allows to leave the context?

**Comment by billthefarmer** [comment]
Well that was a bit of fun. I tested this idea, which doesn't quite work as expected...
```java
            version.setOnClickListener(v ->
                {
                    AlertDialog.Builder builder = new AlertDialog.Builder(context);
                    WebView webView = new WebView(builder.getContext());
                    webView.loadUrl(LATEST);
                    builder.setView(webView);
                    builder.setPositiveButton(android.R.string.ok, null);
                    builder.show();
                });
```
The white line in the dialog is the WebView. Removing the '/latest' from the end of the URL works, probably by removing the redirect, but clicking on anything pops up another 'Open with' dialog.

![device-2019-01-05-155241](https://user-images.githubusercontent.com/3448386/50726259-8aee7180-1102-11e9-9f45-2bf0d38d48cc.png)

![device-2019-01-05-174843](https://user-images.githubusercontent.com/3448386/50727751-5df88980-1117-11e9-9b93-09dbc8bc0923.png)

It's all rather unsatisfactory. The guidance at the top of the WebView docs page says

> In most cases, we recommend using a standard web browser, like Chrome, to deliver content to the user. To learn more about web browsers, read the guide on [invoking a browser with an intent](https://developer.android.com/guide/components/intents-common#Browser).

Of course they would say Chrome. So I will make the the version text a link to the latest release page, which has the advantage that it's consistent with the rest of the dialog, and it's obvious that it's a link, and I can do the same in other apps.

**Comment by marcoM32** [comment]
OK it's good!! thank you very much for the support

**Comment by billthefarmer** [comment]
I've released a new version with a fix
