### ISSUE TITLE
Feature request: open external links in external browser

### ISSUE THREAD

**Issue by citizen2947294** [billthefarmer/diary#82]
If Diary had an option to open external links in an external browser, instead of in the app browser, it would be even more amazing.

**Comment by billthefarmer** [comment]
I will investigate.

**Comment by billthefarmer** [comment]
It turns out that the reason my tryout at #81 didn't work as expected was because you need an associated WebViewClient to handle links. And it behaves thus...
```java
  public boolean shouldOverrideUrlLoading (WebView view,  String url)
```
> Give the host application a chance to take control when a URL is about to be loaded in the current WebView. If a WebViewClient is not provided, by default WebView will ask Activity Manager to choose the proper handler for the URL. If a WebViewClient is provided, returning true causes the current WebView to abort loading the URL, while returning false causes the WebView to continue loading the URL as usual.

So it should be possible.

**Comment by citizen2947294** [comment]
That's the same method I ended up looking at yesterday.

**Comment by billthefarmer** [comment]
That will be in the next version. [Code here](https://github.com/billthefarmer/diary/blob/master/src/main/java/org/billthefarmer/diary/Diary.java#L734).

**Comment by citizen2947294** [comment]
I gave this a try today and it works. This is great. Thank you. :D
