### ISSUE TITLE
App is registered to open locations

### ISSUE THREAD

**Issue by TronFortyTwo** [billthefarmer/diary#83]
Overall description:
The Diary app is opened when a location is opened (for example one sent trought some messaging app)

Steps to reproduce:
- Ask a friend to send you using whatsapp his location
- receive the location message
- click on the location message to open it

Expected behaviour:
The location is not opened using Diary

Actual behaviour
The location is opened using Diary. Once launched, diary will open the calendary panel.

Thanks for the app and for your work!

**Comment by billthefarmer** [comment]
This is intentional. The diary app will insert an OpenStreetMap map if offered a location. If you have another app that can open a [Geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme), you should have been offered a choice.

**Comment by billthefarmer** [comment]
This is intentional. The app will insert an OpenStreetMap map. If you have another app that can accept a [Geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme), you should have been offered a choice.

**Comment by TronFortyTwo** [comment]
Oh ok thanks! sorry for the invalid issue
