### ISSUE TITLE
"Insert timestamp" button

### ISSUE THREAD

**Issue by Kamul-PL** [billthefarmer/diary#84]
I've just discovered Diary. It seems it's quite nice app, but at first glance it lacks some kind of "Insert current time" button, preferably in hh:mm format. Sometimes it's useful to know, when exactly the note was taken. So often when I create my notes, I put a date stamp.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by Kamul-PL** [comment]
That's very good news. Thank you!
