### ISSUE TITLE
Storage path is forced to relative to internal storage

### ISSUE THREAD

**Issue by Almtesh** [billthefarmer/diary#87]
When putting a path for storage starting with `/`, it is ignored and the path is still relative to the internal storage.  
I want to put the diary wherever I want, even on SD card or in app's data.

**Comment by billthefarmer** [comment]
I don't think an ordinary app has permission to store anything anywhere other than in it's private area, it's public area in `Android/data/<app id>` and folders it might set up in the internal storage. If the private or public area is used files may well be deleted if the app is uninstalled. I don't think it has permission to store anything on an SD card that hasn't been converted to internal storage either - see [Editor#65](https://github.com/billthefarmer/editor/issues/65)

**Comment by Almtesh** [comment]
On some devices (including the one I have), you can write on SD card. The best should be to switch to absolute path when path starts with a `/`.

**Comment by billthefarmer** [comment]
I have made this change, with some safeguards. The folder must exist and be writable. That will be in the next version.
