### ISSUE TITLE
Limit image size to display width in markdown view

### ISSUE THREAD

**Issue by spaceChRiS** [billthefarmer/diary#9]
I guess you know the saying “give someone an inch and they'll take a mile”, or, as we say here, “hand someone your pinky and they'll take your hand”. Nevertheless, some little improvements that came to my mind, this being the first one.

First, many thanks for the markdown view, I always dreamt of the possibilities it gives, especially with inserting image links. However, linking my vacation photos in the local file system renders them very large, I guess it is a 1:1 view at the image resolution. It would be great, if the image width would always fit to the display width, and, instead of moving the canvas around, the view would have the opportunity to pinch zoom into the canvas.

Probably this has to be reported upstream, but maybe it is possible by css styling as well. Unfortunately, I was not able to find it out from the markdown view's css documentation.

**Comment by billthefarmer** [comment]
I tried two markdown view libraries. One, [tiagohm/MarkdownView](https://github.com/tiagohm/MarkdownView) has lots of extensions, including sizing images. However it was slow and does the parsing in the UI thread, stopping the app while it does it. Also I couldn't get some of the extensions to work, and I thought it was over the top for a simple diary application. The one I ended up with [falnatsheh/MarkdownView](https://github.com/falnatsheh/MarkdownView) has less functionality, but does the parsing in the background. It also works solidly. I haven't looked at it to see exactly what syntax it supports and what it doesn't.

**Comment by billthefarmer** [comment]
Having had a look online, the answer is to use embedded HTML, so you would use
```html
<img width="100%" src="file:///sdcard/Diary/2017/5/27/myimage.jpg">
```
This is somewhat dated HTML, but it works.

**Comment by billthefarmer** [comment]
I have added a styles.css file which limits the width of images
```css
img {
    max-width: 100%;
}
```
This will be in the next version along with lots of other stuff. However, this poses a problem - whenever I post a new version I get suggestions for things I hadn't thought of. What else useful could be in this css file which won't break anything?

**Comment by spaceChRiS** [comment]
That is great, wonderful, thank you very much. Is this css file located in the user visible tree? If yes, users could tweak such settings by themselves, and you could adapt things into the next version if you find them useful (and if you get the suggestions from the users). If you have the choice to place the css file somewhere, I would suggest `/sdcard/Android/org.billthefarmer.diary/` since it is user and app writable.

**Comment by billthefarmer** [comment]
The CSS file is embedded in the app in the assets folder. There's various discussions on [Stackoverflow](https://stackoverflow.com) about giving users access to facilities which can break things. Markdown is meant to be easy to use and just shows the text if you get it wrong. HTML and CSS are hard and can break if wrong. If a user puts broken HTML or CSS in a page it can break that page, if they put it in a global file it can break all the pages.

**Comment by spaceChRiS** [comment]
To prevent this, there could be a standard `style.css` file that is not visible to the user which is ignored iff there is a `style.css` file in the user directory. That way, it can only be broken by users that are aware of the feature of user-defined styles and removing the user file would always result in the original feature set/style.

Probably, it would be even better if the user additions are added to the original definitions, but that can only work if css has the opportunity to overwrite definitions by the second loaded file. That seems to be the case if I understand https://stackoverflow.com/questions/9459062/in-which-order-do-css-stylesheets-override correctly. So a solution would probably be to just link to two `style.css` files with the one in the user directory being the second. But only if it does not generate an error if the user file is not existent. Otherwise one would have to check the file existence first and add the corresponding link only if it does.

**Comment by billthefarmer** [comment]
The API only allows one styles file. If someone is that desperate for custom styles they can put some HTML in the pages that need it.

**Comment by spaceChRiS** [comment]
I thought it would be easy on HTML level, and not from the API. Probably on CSS level, as documented in https://stackoverflow.com/questions/147500/is-it-possible-to-include-one-css-file-in-another?

Or if you are able to modify the generated HTML, one could hijack the API by entering a known string instead of a URL to the CSS file and replace it by two links:

    <link rel='stylesheet' type='text/css' href='"+ "Known string" +"' />

would become

    <link rel='stylesheet' type='text/css' href='"+ "CSS1-URL" +"' />
    <link rel='stylesheet' type='text/css' href='"+ "CSS2-URL" +"' />

by replacing `Known string` with

    CSS1-URL" +"' />
      <link rel='stylesheet' type='text/css' href='"+ "CSS2-URL

If you think one should take the clean road and add a method with 2 CSS URLs to the API of MarkdownView, I could try to draft a PR there with this option.

The reason that I still think about the topic is that I fear that now that you implemented my suggestion somebody else could request the 1:1 image size. With a user style I could enable this just for me, not bothering others.

**Comment by spaceChRiS** [comment]
What would work anyway is to replace the css link by a link to the user's file iff it exists, before calling `markdownView.loadMarkdownFile()`. The user would be responsible for his css file, but deleting it would restore the original behavior of loading the internal css file. Am I wrong?

**Comment by billthefarmer** [comment]
The next version will include the option of an alternate styles file in `Diary/css/styles.css`. If this file exists, it will be loaded instead of the built in styles file. You can use the `@import` statement to include the built in file using `@import "file:///android_asset/styles.css";` or `@import url("file:///android_asset/styles.css");` in the alternate styles file. Android web view appears to cache the styles, so you have to quit and remove from memory and restart the diary app to pick up style changes.
```css
@import url("file:///android_asset/styles.css");

img {
    max-width: 80%;
}

h2 {
    background: lightblue;
}
```

**Comment by spaceChRiS** [comment]
That's so awesome, I cannot find words. THANK YOU! After all your changes, this app is so much more useful now.

I now got used to this game: 1. My feature request; 2. You tell me that it makes no sense; 3. You tell me that you implemented it; 4. You did a release. :-)

**Comment by billthefarmer** [comment]
There's a couple of reasons for that. One is that I make the mistake of reading what people have written rather than just looking at the heading. They usually say what they really want in the heading and then talk about something slightly different and I get distracted. That was the case  in #6. The second is that what they want is a function of a library I have used in the app, which I would have to fork and update to implement.

**Comment by spaceChRiS** [comment]
That was not meant as criticism, just a funny fact. I am very thankful for your effort in revitalizing this wonderful app :-).
