### ISSUE TITLE
Code for link to date seems broken from German locale

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#90]
My code

```
[22.04.2019 Ostermontag](date:22.04.2019)
```

(Sorry, there are neither formatting buttons here in Android nor a preview, and Github swallows all my code)

results in this display

```
22.04.2019 Ostermontag/2019/04/22.txt)
```

Diary v1.43
Android 6.0.1
System Web View 73.0.3683.90
Moto G4

(Thanks BTW for making individual CSS available, I love this possibility!)

**Comment by billthefarmer** [comment]
I have tested this, I can't reproduce it. I used Deutsch, Deutschland. There is a possible issue that the code checks that the entry exists before redirecting, but that produces a WebView page not available error.

**Comment by uli-on** [comment]
Bill, I've found it: I had renamed the "Diary" folder to "Diary (billthefarmer)" in my app testing phase. That must have confused your app while creating the date links. All is well now and working.
