### ISSUE TITLE
Add some more margin to the editing mode

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#93]
I've a device shelter with edges that cover perhaps one millimeter of the edge of my device. That shelter has a certain thickness, so it's impossible to capture text from the left screen edge, even with a touch pen. This issue makes it a little difficult to populate the index page, where there are lots of these slim square bracket characters for links at the left edge of the display. Some more page margin like 0.5em/3mm would help a lot.

**Comment by billthefarmer** [comment]
OK, I have added margins to the edit view. That will be in the next version.

**Comment by citizen2947294** [comment]
This doesn't work well for all screens. Could you make this an option and place a checkbox in the settings? That would allow the old behavior which works better for other screens.

**Comment by uli-on** [comment]
And a final thank you here, I can move selection handles now to the very screen edge. Great!
