### ISSUE TITLE
"lang" attribute for the body tag

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#94]
Please add a "lang" attribute to the body tag, possibly fetched from the user's global setting for the device's language.

Background: I tried hard to make Diary hyphenate my texts, but even adding a body or html tag to the page with that attribute doesn't work. There are languages with much longer words than English, like French or German, where hyphenation might create a display that's a lot easier to read and much nicer to look at. In German, we have the possibility to concatenate words, like "Nahrungsergänzungsmittel" (food supplements). But even normal words like "argumentieren" (to argue), "eingeschaltet" (turned on) or "entstehen" (to arise) cut holes into a proper margin.

**Comment by uli-on** [comment]
Perhaps I should mention that CSS's "hyphens" needs the lang attribute on an effected page element in order to work.

**Comment by billthefarmer** [comment]
Handling markdown and html is delegated to the [MarkdownView](https://github.com/billthefarmer/MarkdownView) library, which in turn delegates markdown interpretation to the [MarkdownJ](https://github.com/myabc/markdownj) library. I can add a wrapper in MarkdownView to specify the language, according to [W3C](https://www.w3.org/International/questions/qa-html-language-declarations), it should be in the html tag, like this...
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
...
```

**Comment by uli-on** [comment]
It would also work on the HTML element, I think, yes.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by uli-on** [comment]
Thanks also for this one! Unfortunately it doesn't add to hyphenation. I could tell by means of another selector that the lang code is on page. And caniuse says hyphens' "auto" works on webview. Lost, here, pity!

**Comment by uli-on** [comment]
I just read about the reason for not getting hyphenated text: Currently the only language with a hyphenation dictionary in Android Webview is English. 

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Browser_compatibility

**Comment by uli-on** [comment]
> Currently the only language with a hyphenation dictionary in Android Webview is English.

Just wanted to note that in the meantime German is among the languages that are hyphenated, and I love how it made Diary pages more readable and nicer looking :)
