### ISSUE TITLE
use of sd card

### ISSUE THREAD

**Issue by gilcot** [billthefarmer/diary#97]
Diary 1.49 ; Android 5.0

I've switch the default location to my a directory of my SD card (that makes some sync ops easier for me) But I haven't been asked to grant write permission to the app (that works that way with other apps as Google change access rules after Android 4.4) Entries in that new location can be read, but no new entry can be created (hopefully the app doesn't crash, it just fail with a balloon message about access denied)

Regards.

**Comment by billthefarmer** [comment]
As I said here https://github.com/billthefarmer/diary/issues/95#issuecomment-503059339, android only supports using an SD card for sharing or transferring files, unless you make it part of the storage. Some devices seem to allow apps to write to an SD card, but the emulators don't. Therefore, if it works, you are lucky, if it doesn't then it's not supported anyway.
